# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audiotool/comment/v1/comment.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'audiotool/comment/v1/comment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from audiotool.comment.v1 import reaction_pb2 as audiotool_dot_comment_dot_v1_dot_reaction__pb2
from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"audiotool/comment/v1/comment.proto\x12\x14\x61udiotool.comment.v1\x1a#audiotool/comment/v1/reaction.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8a\x08\n\x07\x43omment\x12\x17\n\x04name\x18\x01 \x01(\tB\x03\xe0\x41\x08R\x04name\x12@\n\x0b\x63reate_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x03\xe0\x41\x03R\ncreateTime\x12&\n\x0c\x63reator_name\x18\x03 \x01(\tB\x03\xe0\x41\x03R\x0b\x63reatorName\x12\x17\n\x04text\x18\x04 \x01(\tB\x03\xe0\x41\x02R\x04text\x12@\n\x0bupdate_time\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x03\xe0\x41\x03R\nupdateTime\x12\x1d\n\x07\x64\x65leted\x18\x06 \x01(\x08\x42\x03\xe0\x41\x03R\x07\x64\x65leted\x12\x41\n\treactions\x18\x07 \x03(\x0b\x32\x1e.audiotool.comment.v1.ReactionB\x03\xe0\x41\x03R\treactions\x12&\n\x0f\x66rom_muted_user\x18\x08 \x01(\x08R\rfromMutedUser:\x96\x05\xea\x41\x92\x05\n!comment.api.audiotool.com/Comment\x12!tracks/{track}/comments/{comment}\x12;tracks/{track}/comments/{parent_comment}/comments/{comment}\x12\'playlists/{playlist}/comments/{comment}\x12\x41playlists/{playlist}/comments/{parent_comment}/comments/{comment}\x12#samples/{sample}/comments/{comment}\x12=samples/{sample}/comments/{parent_comment}/comments/{comment}\x12\x1fusers/{user}/comments/{comment}\x12\x39users/{user}/comments/{parent_comment}/comments/{comment}\x12%contests/{contest}/comments/{comment}\x12?contests/{contest}/comments/{parent_comment}/comments/{comment}\x12%projects/{project}/comments/{comment}\x12?projects/{project}/comments/{parent_comment}/comments/{comment}*\x08\x63omments2\x07\x63ommentb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audiotool.comment.v1.comment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMENT'].fields_by_name['name']._loaded_options = None
  _globals['_COMMENT'].fields_by_name['name']._serialized_options = b'\340A\010'
  _globals['_COMMENT'].fields_by_name['create_time']._loaded_options = None
  _globals['_COMMENT'].fields_by_name['create_time']._serialized_options = b'\340A\003'
  _globals['_COMMENT'].fields_by_name['creator_name']._loaded_options = None
  _globals['_COMMENT'].fields_by_name['creator_name']._serialized_options = b'\340A\003'
  _globals['_COMMENT'].fields_by_name['text']._loaded_options = None
  _globals['_COMMENT'].fields_by_name['text']._serialized_options = b'\340A\002'
  _globals['_COMMENT'].fields_by_name['update_time']._loaded_options = None
  _globals['_COMMENT'].fields_by_name['update_time']._serialized_options = b'\340A\003'
  _globals['_COMMENT'].fields_by_name['deleted']._loaded_options = None
  _globals['_COMMENT'].fields_by_name['deleted']._serialized_options = b'\340A\003'
  _globals['_COMMENT'].fields_by_name['reactions']._loaded_options = None
  _globals['_COMMENT'].fields_by_name['reactions']._serialized_options = b'\340A\003'
  _globals['_COMMENT']._loaded_options = None
  _globals['_COMMENT']._serialized_options = b'\352A\222\005\n!comment.api.audiotool.com/Comment\022!tracks/{track}/comments/{comment}\022;tracks/{track}/comments/{parent_comment}/comments/{comment}\022\'playlists/{playlist}/comments/{comment}\022Aplaylists/{playlist}/comments/{parent_comment}/comments/{comment}\022#samples/{sample}/comments/{comment}\022=samples/{sample}/comments/{parent_comment}/comments/{comment}\022\037users/{user}/comments/{comment}\0229users/{user}/comments/{parent_comment}/comments/{comment}\022%contests/{contest}/comments/{comment}\022?contests/{contest}/comments/{parent_comment}/comments/{comment}\022%projects/{project}/comments/{comment}\022?projects/{project}/comments/{parent_comment}/comments/{comment}*\010comments2\007comment'
  _globals['_COMMENT']._serialized_start=191
  _globals['_COMMENT']._serialized_end=1225
# @@protoc_insertion_point(module_scope)
