# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: audiotool/comment/v1/comment_service.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import audiotool.comment.v1.comment_service_pb2 as audiotool_dot_comment_dot_v1_dot_comment__service__pb2


class CommentService(Protocol):
    async def list_comments(self, request: audiotool_dot_comment_dot_v1_dot_comment__service__pb2.ListCommentsRequest, ctx: RequestContext) -> audiotool_dot_comment_dot_v1_dot_comment__service__pb2.ListCommentsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def create_comment(self, request: audiotool_dot_comment_dot_v1_dot_comment__service__pb2.CreateCommentRequest, ctx: RequestContext) -> audiotool_dot_comment_dot_v1_dot_comment__service__pb2.CreateCommentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_comment(self, request: audiotool_dot_comment_dot_v1_dot_comment__service__pb2.GetCommentRequest, ctx: RequestContext) -> audiotool_dot_comment_dot_v1_dot_comment__service__pb2.GetCommentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def update_comment(self, request: audiotool_dot_comment_dot_v1_dot_comment__service__pb2.UpdateCommentRequest, ctx: RequestContext) -> audiotool_dot_comment_dot_v1_dot_comment__service__pb2.UpdateCommentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_comment(self, request: audiotool_dot_comment_dot_v1_dot_comment__service__pb2.DeleteCommentRequest, ctx: RequestContext) -> audiotool_dot_comment_dot_v1_dot_comment__service__pb2.DeleteCommentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_possible_reactions(self, request: audiotool_dot_comment_dot_v1_dot_comment__service__pb2.ListPossibleReactionsRequest, ctx: RequestContext) -> audiotool_dot_comment_dot_v1_dot_comment__service__pb2.ListPossibleReactionsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def add_reaction(self, request: audiotool_dot_comment_dot_v1_dot_comment__service__pb2.AddReactionRequest, ctx: RequestContext) -> audiotool_dot_comment_dot_v1_dot_comment__service__pb2.AddReactionResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def remove_reaction(self, request: audiotool_dot_comment_dot_v1_dot_comment__service__pb2.RemoveReactionRequest, ctx: RequestContext) -> audiotool_dot_comment_dot_v1_dot_comment__service__pb2.RemoveReactionResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class CommentServiceASGIApplication(ConnectASGIApplication[CommentService]):
    def __init__(self, service: CommentService | AsyncGenerator[CommentService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/audiotool.comment.v1.CommentService/ListComments": Endpoint.unary(
                    method=MethodInfo(
                        name="ListComments",
                        service_name="audiotool.comment.v1.CommentService",
                        input=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.ListCommentsRequest,
                        output=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.ListCommentsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_comments,
                ),
                "/audiotool.comment.v1.CommentService/CreateComment": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateComment",
                        service_name="audiotool.comment.v1.CommentService",
                        input=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.CreateCommentRequest,
                        output=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.CreateCommentResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_comment,
                ),
                "/audiotool.comment.v1.CommentService/GetComment": Endpoint.unary(
                    method=MethodInfo(
                        name="GetComment",
                        service_name="audiotool.comment.v1.CommentService",
                        input=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.GetCommentRequest,
                        output=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.GetCommentResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_comment,
                ),
                "/audiotool.comment.v1.CommentService/UpdateComment": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateComment",
                        service_name="audiotool.comment.v1.CommentService",
                        input=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.UpdateCommentRequest,
                        output=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.UpdateCommentResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.update_comment,
                ),
                "/audiotool.comment.v1.CommentService/DeleteComment": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteComment",
                        service_name="audiotool.comment.v1.CommentService",
                        input=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.DeleteCommentRequest,
                        output=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.DeleteCommentResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_comment,
                ),
                "/audiotool.comment.v1.CommentService/ListPossibleReactions": Endpoint.unary(
                    method=MethodInfo(
                        name="ListPossibleReactions",
                        service_name="audiotool.comment.v1.CommentService",
                        input=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.ListPossibleReactionsRequest,
                        output=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.ListPossibleReactionsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_possible_reactions,
                ),
                "/audiotool.comment.v1.CommentService/AddReaction": Endpoint.unary(
                    method=MethodInfo(
                        name="AddReaction",
                        service_name="audiotool.comment.v1.CommentService",
                        input=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.AddReactionRequest,
                        output=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.AddReactionResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.add_reaction,
                ),
                "/audiotool.comment.v1.CommentService/RemoveReaction": Endpoint.unary(
                    method=MethodInfo(
                        name="RemoveReaction",
                        service_name="audiotool.comment.v1.CommentService",
                        input=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.RemoveReactionRequest,
                        output=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.RemoveReactionResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.remove_reaction,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/audiotool.comment.v1.CommentService"


class CommentServiceClient(ConnectClient):
    async def list_comments(
        self,
        request: audiotool_dot_comment_dot_v1_dot_comment__service__pb2.ListCommentsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_comment_dot_v1_dot_comment__service__pb2.ListCommentsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListComments",
                service_name="audiotool.comment.v1.CommentService",
                input=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.ListCommentsRequest,
                output=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.ListCommentsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def create_comment(
        self,
        request: audiotool_dot_comment_dot_v1_dot_comment__service__pb2.CreateCommentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_comment_dot_v1_dot_comment__service__pb2.CreateCommentResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateComment",
                service_name="audiotool.comment.v1.CommentService",
                input=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.CreateCommentRequest,
                output=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.CreateCommentResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_comment(
        self,
        request: audiotool_dot_comment_dot_v1_dot_comment__service__pb2.GetCommentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_comment_dot_v1_dot_comment__service__pb2.GetCommentResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetComment",
                service_name="audiotool.comment.v1.CommentService",
                input=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.GetCommentRequest,
                output=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.GetCommentResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_comment(
        self,
        request: audiotool_dot_comment_dot_v1_dot_comment__service__pb2.UpdateCommentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_comment_dot_v1_dot_comment__service__pb2.UpdateCommentResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateComment",
                service_name="audiotool.comment.v1.CommentService",
                input=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.UpdateCommentRequest,
                output=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.UpdateCommentResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_comment(
        self,
        request: audiotool_dot_comment_dot_v1_dot_comment__service__pb2.DeleteCommentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_comment_dot_v1_dot_comment__service__pb2.DeleteCommentResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteComment",
                service_name="audiotool.comment.v1.CommentService",
                input=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.DeleteCommentRequest,
                output=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.DeleteCommentResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_possible_reactions(
        self,
        request: audiotool_dot_comment_dot_v1_dot_comment__service__pb2.ListPossibleReactionsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_comment_dot_v1_dot_comment__service__pb2.ListPossibleReactionsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListPossibleReactions",
                service_name="audiotool.comment.v1.CommentService",
                input=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.ListPossibleReactionsRequest,
                output=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.ListPossibleReactionsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def add_reaction(
        self,
        request: audiotool_dot_comment_dot_v1_dot_comment__service__pb2.AddReactionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_comment_dot_v1_dot_comment__service__pb2.AddReactionResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="AddReaction",
                service_name="audiotool.comment.v1.CommentService",
                input=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.AddReactionRequest,
                output=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.AddReactionResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def remove_reaction(
        self,
        request: audiotool_dot_comment_dot_v1_dot_comment__service__pb2.RemoveReactionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_comment_dot_v1_dot_comment__service__pb2.RemoveReactionResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RemoveReaction",
                service_name="audiotool.comment.v1.CommentService",
                input=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.RemoveReactionRequest,
                output=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.RemoveReactionResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class CommentServiceSync(Protocol):
    def list_comments(self, request: audiotool_dot_comment_dot_v1_dot_comment__service__pb2.ListCommentsRequest, ctx: RequestContext) -> audiotool_dot_comment_dot_v1_dot_comment__service__pb2.ListCommentsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def create_comment(self, request: audiotool_dot_comment_dot_v1_dot_comment__service__pb2.CreateCommentRequest, ctx: RequestContext) -> audiotool_dot_comment_dot_v1_dot_comment__service__pb2.CreateCommentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_comment(self, request: audiotool_dot_comment_dot_v1_dot_comment__service__pb2.GetCommentRequest, ctx: RequestContext) -> audiotool_dot_comment_dot_v1_dot_comment__service__pb2.GetCommentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def update_comment(self, request: audiotool_dot_comment_dot_v1_dot_comment__service__pb2.UpdateCommentRequest, ctx: RequestContext) -> audiotool_dot_comment_dot_v1_dot_comment__service__pb2.UpdateCommentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_comment(self, request: audiotool_dot_comment_dot_v1_dot_comment__service__pb2.DeleteCommentRequest, ctx: RequestContext) -> audiotool_dot_comment_dot_v1_dot_comment__service__pb2.DeleteCommentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_possible_reactions(self, request: audiotool_dot_comment_dot_v1_dot_comment__service__pb2.ListPossibleReactionsRequest, ctx: RequestContext) -> audiotool_dot_comment_dot_v1_dot_comment__service__pb2.ListPossibleReactionsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def add_reaction(self, request: audiotool_dot_comment_dot_v1_dot_comment__service__pb2.AddReactionRequest, ctx: RequestContext) -> audiotool_dot_comment_dot_v1_dot_comment__service__pb2.AddReactionResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def remove_reaction(self, request: audiotool_dot_comment_dot_v1_dot_comment__service__pb2.RemoveReactionRequest, ctx: RequestContext) -> audiotool_dot_comment_dot_v1_dot_comment__service__pb2.RemoveReactionResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class CommentServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: CommentServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/audiotool.comment.v1.CommentService/ListComments": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListComments",
                        service_name="audiotool.comment.v1.CommentService",
                        input=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.ListCommentsRequest,
                        output=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.ListCommentsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_comments,
                ),
                "/audiotool.comment.v1.CommentService/CreateComment": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateComment",
                        service_name="audiotool.comment.v1.CommentService",
                        input=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.CreateCommentRequest,
                        output=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.CreateCommentResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_comment,
                ),
                "/audiotool.comment.v1.CommentService/GetComment": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetComment",
                        service_name="audiotool.comment.v1.CommentService",
                        input=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.GetCommentRequest,
                        output=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.GetCommentResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_comment,
                ),
                "/audiotool.comment.v1.CommentService/UpdateComment": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateComment",
                        service_name="audiotool.comment.v1.CommentService",
                        input=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.UpdateCommentRequest,
                        output=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.UpdateCommentResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_comment,
                ),
                "/audiotool.comment.v1.CommentService/DeleteComment": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteComment",
                        service_name="audiotool.comment.v1.CommentService",
                        input=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.DeleteCommentRequest,
                        output=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.DeleteCommentResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_comment,
                ),
                "/audiotool.comment.v1.CommentService/ListPossibleReactions": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListPossibleReactions",
                        service_name="audiotool.comment.v1.CommentService",
                        input=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.ListPossibleReactionsRequest,
                        output=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.ListPossibleReactionsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_possible_reactions,
                ),
                "/audiotool.comment.v1.CommentService/AddReaction": EndpointSync.unary(
                    method=MethodInfo(
                        name="AddReaction",
                        service_name="audiotool.comment.v1.CommentService",
                        input=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.AddReactionRequest,
                        output=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.AddReactionResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.add_reaction,
                ),
                "/audiotool.comment.v1.CommentService/RemoveReaction": EndpointSync.unary(
                    method=MethodInfo(
                        name="RemoveReaction",
                        service_name="audiotool.comment.v1.CommentService",
                        input=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.RemoveReactionRequest,
                        output=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.RemoveReactionResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.remove_reaction,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/audiotool.comment.v1.CommentService"


class CommentServiceClientSync(ConnectClientSync):
    def list_comments(
        self,
        request: audiotool_dot_comment_dot_v1_dot_comment__service__pb2.ListCommentsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_comment_dot_v1_dot_comment__service__pb2.ListCommentsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListComments",
                service_name="audiotool.comment.v1.CommentService",
                input=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.ListCommentsRequest,
                output=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.ListCommentsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def create_comment(
        self,
        request: audiotool_dot_comment_dot_v1_dot_comment__service__pb2.CreateCommentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_comment_dot_v1_dot_comment__service__pb2.CreateCommentResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateComment",
                service_name="audiotool.comment.v1.CommentService",
                input=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.CreateCommentRequest,
                output=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.CreateCommentResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_comment(
        self,
        request: audiotool_dot_comment_dot_v1_dot_comment__service__pb2.GetCommentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_comment_dot_v1_dot_comment__service__pb2.GetCommentResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetComment",
                service_name="audiotool.comment.v1.CommentService",
                input=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.GetCommentRequest,
                output=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.GetCommentResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def update_comment(
        self,
        request: audiotool_dot_comment_dot_v1_dot_comment__service__pb2.UpdateCommentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_comment_dot_v1_dot_comment__service__pb2.UpdateCommentResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateComment",
                service_name="audiotool.comment.v1.CommentService",
                input=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.UpdateCommentRequest,
                output=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.UpdateCommentResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_comment(
        self,
        request: audiotool_dot_comment_dot_v1_dot_comment__service__pb2.DeleteCommentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_comment_dot_v1_dot_comment__service__pb2.DeleteCommentResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteComment",
                service_name="audiotool.comment.v1.CommentService",
                input=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.DeleteCommentRequest,
                output=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.DeleteCommentResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_possible_reactions(
        self,
        request: audiotool_dot_comment_dot_v1_dot_comment__service__pb2.ListPossibleReactionsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_comment_dot_v1_dot_comment__service__pb2.ListPossibleReactionsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListPossibleReactions",
                service_name="audiotool.comment.v1.CommentService",
                input=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.ListPossibleReactionsRequest,
                output=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.ListPossibleReactionsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def add_reaction(
        self,
        request: audiotool_dot_comment_dot_v1_dot_comment__service__pb2.AddReactionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_comment_dot_v1_dot_comment__service__pb2.AddReactionResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="AddReaction",
                service_name="audiotool.comment.v1.CommentService",
                input=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.AddReactionRequest,
                output=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.AddReactionResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def remove_reaction(
        self,
        request: audiotool_dot_comment_dot_v1_dot_comment__service__pb2.RemoveReactionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_comment_dot_v1_dot_comment__service__pb2.RemoveReactionResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RemoveReaction",
                service_name="audiotool.comment.v1.CommentService",
                input=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.RemoveReactionRequest,
                output=audiotool_dot_comment_dot_v1_dot_comment__service__pb2.RemoveReactionResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
