# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: audiotool/auth/v1/auth_service.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import audiotool.auth.v1.auth_service_pb2 as audiotool_dot_auth_dot_v1_dot_auth__service__pb2


class AuthService(Protocol):
    async def get_whoami(self, request: audiotool_dot_auth_dot_v1_dot_auth__service__pb2.GetWhoamiRequest, ctx: RequestContext) -> audiotool_dot_auth_dot_v1_dot_auth__service__pb2.GetWhoamiResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_personal_access_tokens(self, request: audiotool_dot_auth_dot_v1_dot_auth__service__pb2.ListPersonalAccessTokensRequest, ctx: RequestContext) -> audiotool_dot_auth_dot_v1_dot_auth__service__pb2.ListPersonalAccessTokensResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def create_personal_access_token(self, request: audiotool_dot_auth_dot_v1_dot_auth__service__pb2.CreatePersonalAccessTokenRequest, ctx: RequestContext) -> audiotool_dot_auth_dot_v1_dot_auth__service__pb2.CreatePersonalAccessTokenResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_personal_access_token(self, request: audiotool_dot_auth_dot_v1_dot_auth__service__pb2.DeletePersonalAccessTokenRequest, ctx: RequestContext) -> audiotool_dot_auth_dot_v1_dot_auth__service__pb2.DeletePersonalAccessTokenResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class AuthServiceASGIApplication(ConnectASGIApplication[AuthService]):
    def __init__(self, service: AuthService | AsyncGenerator[AuthService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/audiotool.auth.v1.AuthService/GetWhoami": Endpoint.unary(
                    method=MethodInfo(
                        name="GetWhoami",
                        service_name="audiotool.auth.v1.AuthService",
                        input=audiotool_dot_auth_dot_v1_dot_auth__service__pb2.GetWhoamiRequest,
                        output=audiotool_dot_auth_dot_v1_dot_auth__service__pb2.GetWhoamiResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_whoami,
                ),
                "/audiotool.auth.v1.AuthService/ListPersonalAccessTokens": Endpoint.unary(
                    method=MethodInfo(
                        name="ListPersonalAccessTokens",
                        service_name="audiotool.auth.v1.AuthService",
                        input=audiotool_dot_auth_dot_v1_dot_auth__service__pb2.ListPersonalAccessTokensRequest,
                        output=audiotool_dot_auth_dot_v1_dot_auth__service__pb2.ListPersonalAccessTokensResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_personal_access_tokens,
                ),
                "/audiotool.auth.v1.AuthService/CreatePersonalAccessToken": Endpoint.unary(
                    method=MethodInfo(
                        name="CreatePersonalAccessToken",
                        service_name="audiotool.auth.v1.AuthService",
                        input=audiotool_dot_auth_dot_v1_dot_auth__service__pb2.CreatePersonalAccessTokenRequest,
                        output=audiotool_dot_auth_dot_v1_dot_auth__service__pb2.CreatePersonalAccessTokenResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_personal_access_token,
                ),
                "/audiotool.auth.v1.AuthService/DeletePersonalAccessToken": Endpoint.unary(
                    method=MethodInfo(
                        name="DeletePersonalAccessToken",
                        service_name="audiotool.auth.v1.AuthService",
                        input=audiotool_dot_auth_dot_v1_dot_auth__service__pb2.DeletePersonalAccessTokenRequest,
                        output=audiotool_dot_auth_dot_v1_dot_auth__service__pb2.DeletePersonalAccessTokenResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_personal_access_token,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/audiotool.auth.v1.AuthService"


class AuthServiceClient(ConnectClient):
    async def get_whoami(
        self,
        request: audiotool_dot_auth_dot_v1_dot_auth__service__pb2.GetWhoamiRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_auth_dot_v1_dot_auth__service__pb2.GetWhoamiResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetWhoami",
                service_name="audiotool.auth.v1.AuthService",
                input=audiotool_dot_auth_dot_v1_dot_auth__service__pb2.GetWhoamiRequest,
                output=audiotool_dot_auth_dot_v1_dot_auth__service__pb2.GetWhoamiResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_personal_access_tokens(
        self,
        request: audiotool_dot_auth_dot_v1_dot_auth__service__pb2.ListPersonalAccessTokensRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_auth_dot_v1_dot_auth__service__pb2.ListPersonalAccessTokensResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListPersonalAccessTokens",
                service_name="audiotool.auth.v1.AuthService",
                input=audiotool_dot_auth_dot_v1_dot_auth__service__pb2.ListPersonalAccessTokensRequest,
                output=audiotool_dot_auth_dot_v1_dot_auth__service__pb2.ListPersonalAccessTokensResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def create_personal_access_token(
        self,
        request: audiotool_dot_auth_dot_v1_dot_auth__service__pb2.CreatePersonalAccessTokenRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_auth_dot_v1_dot_auth__service__pb2.CreatePersonalAccessTokenResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreatePersonalAccessToken",
                service_name="audiotool.auth.v1.AuthService",
                input=audiotool_dot_auth_dot_v1_dot_auth__service__pb2.CreatePersonalAccessTokenRequest,
                output=audiotool_dot_auth_dot_v1_dot_auth__service__pb2.CreatePersonalAccessTokenResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_personal_access_token(
        self,
        request: audiotool_dot_auth_dot_v1_dot_auth__service__pb2.DeletePersonalAccessTokenRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_auth_dot_v1_dot_auth__service__pb2.DeletePersonalAccessTokenResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeletePersonalAccessToken",
                service_name="audiotool.auth.v1.AuthService",
                input=audiotool_dot_auth_dot_v1_dot_auth__service__pb2.DeletePersonalAccessTokenRequest,
                output=audiotool_dot_auth_dot_v1_dot_auth__service__pb2.DeletePersonalAccessTokenResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class AuthServiceSync(Protocol):
    def get_whoami(self, request: audiotool_dot_auth_dot_v1_dot_auth__service__pb2.GetWhoamiRequest, ctx: RequestContext) -> audiotool_dot_auth_dot_v1_dot_auth__service__pb2.GetWhoamiResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_personal_access_tokens(self, request: audiotool_dot_auth_dot_v1_dot_auth__service__pb2.ListPersonalAccessTokensRequest, ctx: RequestContext) -> audiotool_dot_auth_dot_v1_dot_auth__service__pb2.ListPersonalAccessTokensResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def create_personal_access_token(self, request: audiotool_dot_auth_dot_v1_dot_auth__service__pb2.CreatePersonalAccessTokenRequest, ctx: RequestContext) -> audiotool_dot_auth_dot_v1_dot_auth__service__pb2.CreatePersonalAccessTokenResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_personal_access_token(self, request: audiotool_dot_auth_dot_v1_dot_auth__service__pb2.DeletePersonalAccessTokenRequest, ctx: RequestContext) -> audiotool_dot_auth_dot_v1_dot_auth__service__pb2.DeletePersonalAccessTokenResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class AuthServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: AuthServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/audiotool.auth.v1.AuthService/GetWhoami": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetWhoami",
                        service_name="audiotool.auth.v1.AuthService",
                        input=audiotool_dot_auth_dot_v1_dot_auth__service__pb2.GetWhoamiRequest,
                        output=audiotool_dot_auth_dot_v1_dot_auth__service__pb2.GetWhoamiResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_whoami,
                ),
                "/audiotool.auth.v1.AuthService/ListPersonalAccessTokens": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListPersonalAccessTokens",
                        service_name="audiotool.auth.v1.AuthService",
                        input=audiotool_dot_auth_dot_v1_dot_auth__service__pb2.ListPersonalAccessTokensRequest,
                        output=audiotool_dot_auth_dot_v1_dot_auth__service__pb2.ListPersonalAccessTokensResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_personal_access_tokens,
                ),
                "/audiotool.auth.v1.AuthService/CreatePersonalAccessToken": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreatePersonalAccessToken",
                        service_name="audiotool.auth.v1.AuthService",
                        input=audiotool_dot_auth_dot_v1_dot_auth__service__pb2.CreatePersonalAccessTokenRequest,
                        output=audiotool_dot_auth_dot_v1_dot_auth__service__pb2.CreatePersonalAccessTokenResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_personal_access_token,
                ),
                "/audiotool.auth.v1.AuthService/DeletePersonalAccessToken": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeletePersonalAccessToken",
                        service_name="audiotool.auth.v1.AuthService",
                        input=audiotool_dot_auth_dot_v1_dot_auth__service__pb2.DeletePersonalAccessTokenRequest,
                        output=audiotool_dot_auth_dot_v1_dot_auth__service__pb2.DeletePersonalAccessTokenResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_personal_access_token,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/audiotool.auth.v1.AuthService"


class AuthServiceClientSync(ConnectClientSync):
    def get_whoami(
        self,
        request: audiotool_dot_auth_dot_v1_dot_auth__service__pb2.GetWhoamiRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_auth_dot_v1_dot_auth__service__pb2.GetWhoamiResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetWhoami",
                service_name="audiotool.auth.v1.AuthService",
                input=audiotool_dot_auth_dot_v1_dot_auth__service__pb2.GetWhoamiRequest,
                output=audiotool_dot_auth_dot_v1_dot_auth__service__pb2.GetWhoamiResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_personal_access_tokens(
        self,
        request: audiotool_dot_auth_dot_v1_dot_auth__service__pb2.ListPersonalAccessTokensRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_auth_dot_v1_dot_auth__service__pb2.ListPersonalAccessTokensResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListPersonalAccessTokens",
                service_name="audiotool.auth.v1.AuthService",
                input=audiotool_dot_auth_dot_v1_dot_auth__service__pb2.ListPersonalAccessTokensRequest,
                output=audiotool_dot_auth_dot_v1_dot_auth__service__pb2.ListPersonalAccessTokensResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def create_personal_access_token(
        self,
        request: audiotool_dot_auth_dot_v1_dot_auth__service__pb2.CreatePersonalAccessTokenRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_auth_dot_v1_dot_auth__service__pb2.CreatePersonalAccessTokenResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreatePersonalAccessToken",
                service_name="audiotool.auth.v1.AuthService",
                input=audiotool_dot_auth_dot_v1_dot_auth__service__pb2.CreatePersonalAccessTokenRequest,
                output=audiotool_dot_auth_dot_v1_dot_auth__service__pb2.CreatePersonalAccessTokenResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_personal_access_token(
        self,
        request: audiotool_dot_auth_dot_v1_dot_auth__service__pb2.DeletePersonalAccessTokenRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_auth_dot_v1_dot_auth__service__pb2.DeletePersonalAccessTokenResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeletePersonalAccessToken",
                service_name="audiotool.auth.v1.AuthService",
                input=audiotool_dot_auth_dot_v1_dot_auth__service__pb2.DeletePersonalAccessTokenRequest,
                output=audiotool_dot_auth_dot_v1_dot_auth__service__pb2.DeletePersonalAccessTokenResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
