# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: audiotool/sample/v1/sample_service.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import audiotool.sample.v1.sample_service_pb2 as audiotool_dot_sample_dot_v1_dot_sample__service__pb2


class SampleService(Protocol):
    async def list_samples(self, request: audiotool_dot_sample_dot_v1_dot_sample__service__pb2.ListSamplesRequest, ctx: RequestContext) -> audiotool_dot_sample_dot_v1_dot_sample__service__pb2.ListSamplesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def create_sample(self, request: audiotool_dot_sample_dot_v1_dot_sample__service__pb2.CreateSampleRequest, ctx: RequestContext) -> audiotool_dot_sample_dot_v1_dot_sample__service__pb2.CreateSampleResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def upload_sample_finished(self, request: audiotool_dot_sample_dot_v1_dot_sample__service__pb2.UploadSampleFinishedRequest, ctx: RequestContext) -> audiotool_dot_sample_dot_v1_dot_sample__service__pb2.UploadSampleFinishedResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_sample(self, request: audiotool_dot_sample_dot_v1_dot_sample__service__pb2.GetSampleRequest, ctx: RequestContext) -> audiotool_dot_sample_dot_v1_dot_sample__service__pb2.GetSampleResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def update_sample(self, request: audiotool_dot_sample_dot_v1_dot_sample__service__pb2.UpdateSampleRequest, ctx: RequestContext) -> audiotool_dot_sample_dot_v1_dot_sample__service__pb2.UpdateSampleResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_sample(self, request: audiotool_dot_sample_dot_v1_dot_sample__service__pb2.DeleteSampleRequest, ctx: RequestContext) -> audiotool_dot_sample_dot_v1_dot_sample__service__pb2.DeleteSampleResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def listen(self, request: audiotool_dot_sample_dot_v1_dot_sample__service__pb2.ListenRequest, ctx: RequestContext) -> AsyncIterator[audiotool_dot_sample_dot_v1_dot_sample__service__pb2.ListenResponse]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class SampleServiceASGIApplication(ConnectASGIApplication[SampleService]):
    def __init__(self, service: SampleService | AsyncGenerator[SampleService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/audiotool.sample.v1.SampleService/ListSamples": Endpoint.unary(
                    method=MethodInfo(
                        name="ListSamples",
                        service_name="audiotool.sample.v1.SampleService",
                        input=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.ListSamplesRequest,
                        output=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.ListSamplesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_samples,
                ),
                "/audiotool.sample.v1.SampleService/CreateSample": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateSample",
                        service_name="audiotool.sample.v1.SampleService",
                        input=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.CreateSampleRequest,
                        output=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.CreateSampleResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_sample,
                ),
                "/audiotool.sample.v1.SampleService/UploadSampleFinished": Endpoint.unary(
                    method=MethodInfo(
                        name="UploadSampleFinished",
                        service_name="audiotool.sample.v1.SampleService",
                        input=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.UploadSampleFinishedRequest,
                        output=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.UploadSampleFinishedResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.upload_sample_finished,
                ),
                "/audiotool.sample.v1.SampleService/GetSample": Endpoint.unary(
                    method=MethodInfo(
                        name="GetSample",
                        service_name="audiotool.sample.v1.SampleService",
                        input=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.GetSampleRequest,
                        output=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.GetSampleResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_sample,
                ),
                "/audiotool.sample.v1.SampleService/UpdateSample": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateSample",
                        service_name="audiotool.sample.v1.SampleService",
                        input=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.UpdateSampleRequest,
                        output=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.UpdateSampleResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.update_sample,
                ),
                "/audiotool.sample.v1.SampleService/DeleteSample": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteSample",
                        service_name="audiotool.sample.v1.SampleService",
                        input=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.DeleteSampleRequest,
                        output=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.DeleteSampleResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_sample,
                ),
                "/audiotool.sample.v1.SampleService/Listen": Endpoint.server_stream(
                    method=MethodInfo(
                        name="Listen",
                        service_name="audiotool.sample.v1.SampleService",
                        input=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.ListenRequest,
                        output=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.ListenResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.listen,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/audiotool.sample.v1.SampleService"


class SampleServiceClient(ConnectClient):
    async def list_samples(
        self,
        request: audiotool_dot_sample_dot_v1_dot_sample__service__pb2.ListSamplesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_sample_dot_v1_dot_sample__service__pb2.ListSamplesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListSamples",
                service_name="audiotool.sample.v1.SampleService",
                input=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.ListSamplesRequest,
                output=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.ListSamplesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def create_sample(
        self,
        request: audiotool_dot_sample_dot_v1_dot_sample__service__pb2.CreateSampleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_sample_dot_v1_dot_sample__service__pb2.CreateSampleResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateSample",
                service_name="audiotool.sample.v1.SampleService",
                input=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.CreateSampleRequest,
                output=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.CreateSampleResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def upload_sample_finished(
        self,
        request: audiotool_dot_sample_dot_v1_dot_sample__service__pb2.UploadSampleFinishedRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_sample_dot_v1_dot_sample__service__pb2.UploadSampleFinishedResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UploadSampleFinished",
                service_name="audiotool.sample.v1.SampleService",
                input=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.UploadSampleFinishedRequest,
                output=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.UploadSampleFinishedResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_sample(
        self,
        request: audiotool_dot_sample_dot_v1_dot_sample__service__pb2.GetSampleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_sample_dot_v1_dot_sample__service__pb2.GetSampleResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetSample",
                service_name="audiotool.sample.v1.SampleService",
                input=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.GetSampleRequest,
                output=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.GetSampleResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_sample(
        self,
        request: audiotool_dot_sample_dot_v1_dot_sample__service__pb2.UpdateSampleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_sample_dot_v1_dot_sample__service__pb2.UpdateSampleResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateSample",
                service_name="audiotool.sample.v1.SampleService",
                input=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.UpdateSampleRequest,
                output=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.UpdateSampleResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_sample(
        self,
        request: audiotool_dot_sample_dot_v1_dot_sample__service__pb2.DeleteSampleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_sample_dot_v1_dot_sample__service__pb2.DeleteSampleResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteSample",
                service_name="audiotool.sample.v1.SampleService",
                input=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.DeleteSampleRequest,
                output=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.DeleteSampleResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def listen(
        self,
        request: audiotool_dot_sample_dot_v1_dot_sample__service__pb2.ListenRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> AsyncIterator[audiotool_dot_sample_dot_v1_dot_sample__service__pb2.ListenResponse]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="Listen",
                service_name="audiotool.sample.v1.SampleService",
                input=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.ListenRequest,
                output=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.ListenResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class SampleServiceSync(Protocol):
    def list_samples(self, request: audiotool_dot_sample_dot_v1_dot_sample__service__pb2.ListSamplesRequest, ctx: RequestContext) -> audiotool_dot_sample_dot_v1_dot_sample__service__pb2.ListSamplesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def create_sample(self, request: audiotool_dot_sample_dot_v1_dot_sample__service__pb2.CreateSampleRequest, ctx: RequestContext) -> audiotool_dot_sample_dot_v1_dot_sample__service__pb2.CreateSampleResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def upload_sample_finished(self, request: audiotool_dot_sample_dot_v1_dot_sample__service__pb2.UploadSampleFinishedRequest, ctx: RequestContext) -> audiotool_dot_sample_dot_v1_dot_sample__service__pb2.UploadSampleFinishedResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_sample(self, request: audiotool_dot_sample_dot_v1_dot_sample__service__pb2.GetSampleRequest, ctx: RequestContext) -> audiotool_dot_sample_dot_v1_dot_sample__service__pb2.GetSampleResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def update_sample(self, request: audiotool_dot_sample_dot_v1_dot_sample__service__pb2.UpdateSampleRequest, ctx: RequestContext) -> audiotool_dot_sample_dot_v1_dot_sample__service__pb2.UpdateSampleResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_sample(self, request: audiotool_dot_sample_dot_v1_dot_sample__service__pb2.DeleteSampleRequest, ctx: RequestContext) -> audiotool_dot_sample_dot_v1_dot_sample__service__pb2.DeleteSampleResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def listen(self, request: audiotool_dot_sample_dot_v1_dot_sample__service__pb2.ListenRequest, ctx: RequestContext) -> Iterator[audiotool_dot_sample_dot_v1_dot_sample__service__pb2.ListenResponse]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class SampleServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: SampleServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/audiotool.sample.v1.SampleService/ListSamples": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListSamples",
                        service_name="audiotool.sample.v1.SampleService",
                        input=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.ListSamplesRequest,
                        output=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.ListSamplesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_samples,
                ),
                "/audiotool.sample.v1.SampleService/CreateSample": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateSample",
                        service_name="audiotool.sample.v1.SampleService",
                        input=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.CreateSampleRequest,
                        output=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.CreateSampleResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_sample,
                ),
                "/audiotool.sample.v1.SampleService/UploadSampleFinished": EndpointSync.unary(
                    method=MethodInfo(
                        name="UploadSampleFinished",
                        service_name="audiotool.sample.v1.SampleService",
                        input=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.UploadSampleFinishedRequest,
                        output=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.UploadSampleFinishedResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.upload_sample_finished,
                ),
                "/audiotool.sample.v1.SampleService/GetSample": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetSample",
                        service_name="audiotool.sample.v1.SampleService",
                        input=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.GetSampleRequest,
                        output=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.GetSampleResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_sample,
                ),
                "/audiotool.sample.v1.SampleService/UpdateSample": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateSample",
                        service_name="audiotool.sample.v1.SampleService",
                        input=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.UpdateSampleRequest,
                        output=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.UpdateSampleResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_sample,
                ),
                "/audiotool.sample.v1.SampleService/DeleteSample": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteSample",
                        service_name="audiotool.sample.v1.SampleService",
                        input=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.DeleteSampleRequest,
                        output=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.DeleteSampleResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_sample,
                ),
                "/audiotool.sample.v1.SampleService/Listen": EndpointSync.server_stream(
                    method=MethodInfo(
                        name="Listen",
                        service_name="audiotool.sample.v1.SampleService",
                        input=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.ListenRequest,
                        output=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.ListenResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.listen,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/audiotool.sample.v1.SampleService"


class SampleServiceClientSync(ConnectClientSync):
    def list_samples(
        self,
        request: audiotool_dot_sample_dot_v1_dot_sample__service__pb2.ListSamplesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_sample_dot_v1_dot_sample__service__pb2.ListSamplesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListSamples",
                service_name="audiotool.sample.v1.SampleService",
                input=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.ListSamplesRequest,
                output=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.ListSamplesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def create_sample(
        self,
        request: audiotool_dot_sample_dot_v1_dot_sample__service__pb2.CreateSampleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_sample_dot_v1_dot_sample__service__pb2.CreateSampleResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateSample",
                service_name="audiotool.sample.v1.SampleService",
                input=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.CreateSampleRequest,
                output=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.CreateSampleResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def upload_sample_finished(
        self,
        request: audiotool_dot_sample_dot_v1_dot_sample__service__pb2.UploadSampleFinishedRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_sample_dot_v1_dot_sample__service__pb2.UploadSampleFinishedResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UploadSampleFinished",
                service_name="audiotool.sample.v1.SampleService",
                input=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.UploadSampleFinishedRequest,
                output=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.UploadSampleFinishedResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_sample(
        self,
        request: audiotool_dot_sample_dot_v1_dot_sample__service__pb2.GetSampleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_sample_dot_v1_dot_sample__service__pb2.GetSampleResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetSample",
                service_name="audiotool.sample.v1.SampleService",
                input=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.GetSampleRequest,
                output=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.GetSampleResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def update_sample(
        self,
        request: audiotool_dot_sample_dot_v1_dot_sample__service__pb2.UpdateSampleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_sample_dot_v1_dot_sample__service__pb2.UpdateSampleResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateSample",
                service_name="audiotool.sample.v1.SampleService",
                input=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.UpdateSampleRequest,
                output=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.UpdateSampleResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_sample(
        self,
        request: audiotool_dot_sample_dot_v1_dot_sample__service__pb2.DeleteSampleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_sample_dot_v1_dot_sample__service__pb2.DeleteSampleResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteSample",
                service_name="audiotool.sample.v1.SampleService",
                input=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.DeleteSampleRequest,
                output=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.DeleteSampleResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def listen(
        self,
        request: audiotool_dot_sample_dot_v1_dot_sample__service__pb2.ListenRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> Iterator[audiotool_dot_sample_dot_v1_dot_sample__service__pb2.ListenResponse]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="Listen",
                service_name="audiotool.sample.v1.SampleService",
                input=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.ListenRequest,
                output=audiotool_dot_sample_dot_v1_dot_sample__service__pb2.ListenResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
