# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audiotool/sample/v1/sample_event.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'audiotool/sample/v1/sample_event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from audiotool.sample.v1 import sample_pb2 as audiotool_dot_sample_dot_v1_dot_sample__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&audiotool/sample/v1/sample_event.proto\x12\x13\x61udiotool.sample.v1\x1a audiotool/sample/v1/sample.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbd\x01\n\x0bSampleEvent\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12;\n\x0b\x63reate_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\ncreateTime\x12X\n\x13sample_convert_done\x18\x03 \x01(\x0b\x32&.audiotool.sample.v1.SampleConvertDoneH\x00R\x11sampleConvertDoneB\x07\n\x05\x65vent\"\x8f\x01\n\x11SampleConvertDone\x12\x33\n\x06sample\x18\x01 \x01(\x0b\x32\x1b.audiotool.sample.v1.SampleR\x06sample\x12\x45\n\x05\x65rror\x18\x02 \x01(\x0e\x32/.audiotool.sample.v1.SampleConvertDoneErrorTypeR\x05\x65rror*\xd4\x01\n\x1aSampleConvertDoneErrorType\x12.\n*SAMPLE_CONVERT_DONE_ERROR_TYPE_UNSPECIFIED\x10\x00\x12\'\n#SAMPLE_CONVERT_DONE_ERROR_TYPE_NONE\x10\x01\x12\x30\n,SAMPLE_CONVERT_DONE_ERROR_TYPE_INVALID_INPUT\x10\x02\x12+\n\'SAMPLE_CONVERT_DONE_ERROR_TYPE_INTERNAL\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audiotool.sample.v1.sample_event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SAMPLECONVERTDONEERRORTYPE']._serialized_start=469
  _globals['_SAMPLECONVERTDONEERRORTYPE']._serialized_end=681
  _globals['_SAMPLEEVENT']._serialized_start=131
  _globals['_SAMPLEEVENT']._serialized_end=320
  _globals['_SAMPLECONVERTDONE']._serialized_start=323
  _globals['_SAMPLECONVERTDONE']._serialized_end=466
# @@protoc_insertion_point(module_scope)
