# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: audiotool/audiograph/v1/audiograph_service.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import audiotool.audiograph.v1.audiograph_service_pb2 as audiotool_dot_audiograph_dot_v1_dot_audiograph__service__pb2


class AudiographService(Protocol):
    async def get_audiographs(self, request: audiotool_dot_audiograph_dot_v1_dot_audiograph__service__pb2.GetAudiographsRequest, ctx: RequestContext) -> audiotool_dot_audiograph_dot_v1_dot_audiograph__service__pb2.GetAudiographsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class AudiographServiceASGIApplication(ConnectASGIApplication[AudiographService]):
    def __init__(self, service: AudiographService | AsyncGenerator[AudiographService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/audiotool.audiograph.v1.AudiographService/GetAudiographs": Endpoint.unary(
                    method=MethodInfo(
                        name="GetAudiographs",
                        service_name="audiotool.audiograph.v1.AudiographService",
                        input=audiotool_dot_audiograph_dot_v1_dot_audiograph__service__pb2.GetAudiographsRequest,
                        output=audiotool_dot_audiograph_dot_v1_dot_audiograph__service__pb2.GetAudiographsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_audiographs,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/audiotool.audiograph.v1.AudiographService"


class AudiographServiceClient(ConnectClient):
    async def get_audiographs(
        self,
        request: audiotool_dot_audiograph_dot_v1_dot_audiograph__service__pb2.GetAudiographsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_audiograph_dot_v1_dot_audiograph__service__pb2.GetAudiographsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetAudiographs",
                service_name="audiotool.audiograph.v1.AudiographService",
                input=audiotool_dot_audiograph_dot_v1_dot_audiograph__service__pb2.GetAudiographsRequest,
                output=audiotool_dot_audiograph_dot_v1_dot_audiograph__service__pb2.GetAudiographsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class AudiographServiceSync(Protocol):
    def get_audiographs(self, request: audiotool_dot_audiograph_dot_v1_dot_audiograph__service__pb2.GetAudiographsRequest, ctx: RequestContext) -> audiotool_dot_audiograph_dot_v1_dot_audiograph__service__pb2.GetAudiographsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class AudiographServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: AudiographServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/audiotool.audiograph.v1.AudiographService/GetAudiographs": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetAudiographs",
                        service_name="audiotool.audiograph.v1.AudiographService",
                        input=audiotool_dot_audiograph_dot_v1_dot_audiograph__service__pb2.GetAudiographsRequest,
                        output=audiotool_dot_audiograph_dot_v1_dot_audiograph__service__pb2.GetAudiographsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_audiographs,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/audiotool.audiograph.v1.AudiographService"


class AudiographServiceClientSync(ConnectClientSync):
    def get_audiographs(
        self,
        request: audiotool_dot_audiograph_dot_v1_dot_audiograph__service__pb2.GetAudiographsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_audiograph_dot_v1_dot_audiograph__service__pb2.GetAudiographsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetAudiographs",
                service_name="audiotool.audiograph.v1.AudiographService",
                input=audiotool_dot_audiograph_dot_v1_dot_audiograph__service__pb2.GetAudiographsRequest,
                output=audiotool_dot_audiograph_dot_v1_dot_audiograph__service__pb2.GetAudiographsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
