# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audiotool/audiograph/v1/audiograph.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'audiotool/audiograph/v1/audiograph.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(audiotool/audiograph/v1/audiograph.proto\x12\x17\x61udiotool.audiograph.v1\"\x1f\n\x05Graph\x12\x16\n\x06values\x18\x01 \x03(\rR\x06values\"i\n\nAudiograph\x12#\n\rresource_name\x18\x01 \x01(\tR\x0cresourceName\x12\x36\n\x06graphs\x18\x02 \x03(\x0b\x32\x1e.audiotool.audiograph.v1.GraphR\x06graphsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audiotool.audiograph.v1.audiograph_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GRAPH']._serialized_start=69
  _globals['_GRAPH']._serialized_end=100
  _globals['_AUDIOGRAPH']._serialized_start=102
  _globals['_AUDIOGRAPH']._serialized_end=207
# @@protoc_insertion_point(module_scope)
