# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audiotool/audiograph/v1/audiograph_service.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'audiotool/audiograph/v1/audiograph_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from audiotool.audiograph.v1 import audiograph_pb2 as audiotool_dot_audiograph_dot_v1_dot_audiograph__pb2
from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0audiotool/audiograph/v1/audiograph_service.proto\x12\x17\x61udiotool.audiograph.v1\x1a(audiotool/audiograph/v1/audiograph.proto\x1a\x1fgoogle/api/field_behavior.proto\"\xe1\x01\n\x15GetAudiographsRequest\x12*\n\x0eresource_names\x18\x01 \x03(\tB\x03\xe0\x41\x02R\rresourceNames\x12P\n\nresolution\x18\x02 \x01(\x0e\x32\x30.audiotool.audiograph.v1.GetAudiographResolutionR\nresolution\x12J\n\x08\x63hannels\x18\x03 \x01(\x0e\x32..audiotool.audiograph.v1.GetAudiographChannelsR\x08\x63hannels\"_\n\x16GetAudiographsResponse\x12\x45\n\x0b\x61udiographs\x18\x01 \x03(\x0b\x32#.audiotool.audiograph.v1.AudiographR\x0b\x61udiographs*\x9d\x02\n\x17GetAudiographResolution\x12)\n%GET_AUDIOGRAPH_RESOLUTION_UNSPECIFIED\x10\x00\x12!\n\x1dGET_AUDIOGRAPH_RESOLUTION_120\x10x\x12\"\n\x1dGET_AUDIOGRAPH_RESOLUTION_240\x10\xf0\x01\x12\"\n\x1dGET_AUDIOGRAPH_RESOLUTION_480\x10\xe0\x03\x12\"\n\x1dGET_AUDIOGRAPH_RESOLUTION_960\x10\xc0\x07\x12#\n\x1eGET_AUDIOGRAPH_RESOLUTION_1920\x10\x80\x0f\x12#\n\x1eGET_AUDIOGRAPH_RESOLUTION_3840\x10\x80\x1e*\x86\x01\n\x15GetAudiographChannels\x12\'\n#GET_AUDIOGRAPH_CHANNELS_UNSPECIFIED\x10\x00\x12 \n\x1cGET_AUDIOGRAPH_CHANNELS_MONO\x10\x01\x12\"\n\x1eGET_AUDIOGRAPH_CHANNELS_STEREO\x10\x02\x32\x88\x01\n\x11\x41udiographService\x12s\n\x0eGetAudiographs\x12..audiotool.audiograph.v1.GetAudiographsRequest\x1a/.audiotool.audiograph.v1.GetAudiographsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audiotool.audiograph.v1.audiograph_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETAUDIOGRAPHSREQUEST'].fields_by_name['resource_names']._loaded_options = None
  _globals['_GETAUDIOGRAPHSREQUEST'].fields_by_name['resource_names']._serialized_options = b'\340A\002'
  _globals['_GETAUDIOGRAPHRESOLUTION']._serialized_start=478
  _globals['_GETAUDIOGRAPHRESOLUTION']._serialized_end=763
  _globals['_GETAUDIOGRAPHCHANNELS']._serialized_start=766
  _globals['_GETAUDIOGRAPHCHANNELS']._serialized_end=900
  _globals['_GETAUDIOGRAPHSREQUEST']._serialized_start=153
  _globals['_GETAUDIOGRAPHSREQUEST']._serialized_end=378
  _globals['_GETAUDIOGRAPHSRESPONSE']._serialized_start=380
  _globals['_GETAUDIOGRAPHSRESPONSE']._serialized_end=475
  _globals['_AUDIOGRAPHSERVICE']._serialized_start=903
  _globals['_AUDIOGRAPHSERVICE']._serialized_end=1039
# @@protoc_insertion_point(module_scope)
