# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: audiotool/longrunning/v1/operation.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import audiotool.longrunning.v1.operation_pb2 as audiotool_dot_longrunning_dot_v1_dot_operation__pb2


class OperationService(Protocol):
    async def list_operations(self, request: audiotool_dot_longrunning_dot_v1_dot_operation__pb2.ListOperationsRequest, ctx: RequestContext) -> audiotool_dot_longrunning_dot_v1_dot_operation__pb2.ListOperationsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_operation(self, request: audiotool_dot_longrunning_dot_v1_dot_operation__pb2.GetOperationRequest, ctx: RequestContext) -> audiotool_dot_longrunning_dot_v1_dot_operation__pb2.GetOperationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_operation(self, request: audiotool_dot_longrunning_dot_v1_dot_operation__pb2.DeleteOperationRequest, ctx: RequestContext) -> audiotool_dot_longrunning_dot_v1_dot_operation__pb2.DeleteOperationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def cancel_operation(self, request: audiotool_dot_longrunning_dot_v1_dot_operation__pb2.CancelOperationRequest, ctx: RequestContext) -> audiotool_dot_longrunning_dot_v1_dot_operation__pb2.CancelOperationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class OperationServiceASGIApplication(ConnectASGIApplication[OperationService]):
    def __init__(self, service: OperationService | AsyncGenerator[OperationService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/audiotool.longrunning.v1.OperationService/ListOperations": Endpoint.unary(
                    method=MethodInfo(
                        name="ListOperations",
                        service_name="audiotool.longrunning.v1.OperationService",
                        input=audiotool_dot_longrunning_dot_v1_dot_operation__pb2.ListOperationsRequest,
                        output=audiotool_dot_longrunning_dot_v1_dot_operation__pb2.ListOperationsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_operations,
                ),
                "/audiotool.longrunning.v1.OperationService/GetOperation": Endpoint.unary(
                    method=MethodInfo(
                        name="GetOperation",
                        service_name="audiotool.longrunning.v1.OperationService",
                        input=audiotool_dot_longrunning_dot_v1_dot_operation__pb2.GetOperationRequest,
                        output=audiotool_dot_longrunning_dot_v1_dot_operation__pb2.GetOperationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_operation,
                ),
                "/audiotool.longrunning.v1.OperationService/DeleteOperation": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteOperation",
                        service_name="audiotool.longrunning.v1.OperationService",
                        input=audiotool_dot_longrunning_dot_v1_dot_operation__pb2.DeleteOperationRequest,
                        output=audiotool_dot_longrunning_dot_v1_dot_operation__pb2.DeleteOperationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_operation,
                ),
                "/audiotool.longrunning.v1.OperationService/CancelOperation": Endpoint.unary(
                    method=MethodInfo(
                        name="CancelOperation",
                        service_name="audiotool.longrunning.v1.OperationService",
                        input=audiotool_dot_longrunning_dot_v1_dot_operation__pb2.CancelOperationRequest,
                        output=audiotool_dot_longrunning_dot_v1_dot_operation__pb2.CancelOperationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.cancel_operation,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/audiotool.longrunning.v1.OperationService"


class OperationServiceClient(ConnectClient):
    async def list_operations(
        self,
        request: audiotool_dot_longrunning_dot_v1_dot_operation__pb2.ListOperationsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_longrunning_dot_v1_dot_operation__pb2.ListOperationsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListOperations",
                service_name="audiotool.longrunning.v1.OperationService",
                input=audiotool_dot_longrunning_dot_v1_dot_operation__pb2.ListOperationsRequest,
                output=audiotool_dot_longrunning_dot_v1_dot_operation__pb2.ListOperationsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_operation(
        self,
        request: audiotool_dot_longrunning_dot_v1_dot_operation__pb2.GetOperationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_longrunning_dot_v1_dot_operation__pb2.GetOperationResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetOperation",
                service_name="audiotool.longrunning.v1.OperationService",
                input=audiotool_dot_longrunning_dot_v1_dot_operation__pb2.GetOperationRequest,
                output=audiotool_dot_longrunning_dot_v1_dot_operation__pb2.GetOperationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_operation(
        self,
        request: audiotool_dot_longrunning_dot_v1_dot_operation__pb2.DeleteOperationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_longrunning_dot_v1_dot_operation__pb2.DeleteOperationResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteOperation",
                service_name="audiotool.longrunning.v1.OperationService",
                input=audiotool_dot_longrunning_dot_v1_dot_operation__pb2.DeleteOperationRequest,
                output=audiotool_dot_longrunning_dot_v1_dot_operation__pb2.DeleteOperationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def cancel_operation(
        self,
        request: audiotool_dot_longrunning_dot_v1_dot_operation__pb2.CancelOperationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_longrunning_dot_v1_dot_operation__pb2.CancelOperationResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CancelOperation",
                service_name="audiotool.longrunning.v1.OperationService",
                input=audiotool_dot_longrunning_dot_v1_dot_operation__pb2.CancelOperationRequest,
                output=audiotool_dot_longrunning_dot_v1_dot_operation__pb2.CancelOperationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class OperationServiceSync(Protocol):
    def list_operations(self, request: audiotool_dot_longrunning_dot_v1_dot_operation__pb2.ListOperationsRequest, ctx: RequestContext) -> audiotool_dot_longrunning_dot_v1_dot_operation__pb2.ListOperationsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_operation(self, request: audiotool_dot_longrunning_dot_v1_dot_operation__pb2.GetOperationRequest, ctx: RequestContext) -> audiotool_dot_longrunning_dot_v1_dot_operation__pb2.GetOperationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_operation(self, request: audiotool_dot_longrunning_dot_v1_dot_operation__pb2.DeleteOperationRequest, ctx: RequestContext) -> audiotool_dot_longrunning_dot_v1_dot_operation__pb2.DeleteOperationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def cancel_operation(self, request: audiotool_dot_longrunning_dot_v1_dot_operation__pb2.CancelOperationRequest, ctx: RequestContext) -> audiotool_dot_longrunning_dot_v1_dot_operation__pb2.CancelOperationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class OperationServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: OperationServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/audiotool.longrunning.v1.OperationService/ListOperations": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListOperations",
                        service_name="audiotool.longrunning.v1.OperationService",
                        input=audiotool_dot_longrunning_dot_v1_dot_operation__pb2.ListOperationsRequest,
                        output=audiotool_dot_longrunning_dot_v1_dot_operation__pb2.ListOperationsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_operations,
                ),
                "/audiotool.longrunning.v1.OperationService/GetOperation": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetOperation",
                        service_name="audiotool.longrunning.v1.OperationService",
                        input=audiotool_dot_longrunning_dot_v1_dot_operation__pb2.GetOperationRequest,
                        output=audiotool_dot_longrunning_dot_v1_dot_operation__pb2.GetOperationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_operation,
                ),
                "/audiotool.longrunning.v1.OperationService/DeleteOperation": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteOperation",
                        service_name="audiotool.longrunning.v1.OperationService",
                        input=audiotool_dot_longrunning_dot_v1_dot_operation__pb2.DeleteOperationRequest,
                        output=audiotool_dot_longrunning_dot_v1_dot_operation__pb2.DeleteOperationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_operation,
                ),
                "/audiotool.longrunning.v1.OperationService/CancelOperation": EndpointSync.unary(
                    method=MethodInfo(
                        name="CancelOperation",
                        service_name="audiotool.longrunning.v1.OperationService",
                        input=audiotool_dot_longrunning_dot_v1_dot_operation__pb2.CancelOperationRequest,
                        output=audiotool_dot_longrunning_dot_v1_dot_operation__pb2.CancelOperationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.cancel_operation,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/audiotool.longrunning.v1.OperationService"


class OperationServiceClientSync(ConnectClientSync):
    def list_operations(
        self,
        request: audiotool_dot_longrunning_dot_v1_dot_operation__pb2.ListOperationsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_longrunning_dot_v1_dot_operation__pb2.ListOperationsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListOperations",
                service_name="audiotool.longrunning.v1.OperationService",
                input=audiotool_dot_longrunning_dot_v1_dot_operation__pb2.ListOperationsRequest,
                output=audiotool_dot_longrunning_dot_v1_dot_operation__pb2.ListOperationsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_operation(
        self,
        request: audiotool_dot_longrunning_dot_v1_dot_operation__pb2.GetOperationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_longrunning_dot_v1_dot_operation__pb2.GetOperationResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetOperation",
                service_name="audiotool.longrunning.v1.OperationService",
                input=audiotool_dot_longrunning_dot_v1_dot_operation__pb2.GetOperationRequest,
                output=audiotool_dot_longrunning_dot_v1_dot_operation__pb2.GetOperationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_operation(
        self,
        request: audiotool_dot_longrunning_dot_v1_dot_operation__pb2.DeleteOperationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_longrunning_dot_v1_dot_operation__pb2.DeleteOperationResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteOperation",
                service_name="audiotool.longrunning.v1.OperationService",
                input=audiotool_dot_longrunning_dot_v1_dot_operation__pb2.DeleteOperationRequest,
                output=audiotool_dot_longrunning_dot_v1_dot_operation__pb2.DeleteOperationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def cancel_operation(
        self,
        request: audiotool_dot_longrunning_dot_v1_dot_operation__pb2.CancelOperationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_longrunning_dot_v1_dot_operation__pb2.CancelOperationResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CancelOperation",
                service_name="audiotool.longrunning.v1.OperationService",
                input=audiotool_dot_longrunning_dot_v1_dot_operation__pb2.CancelOperationRequest,
                output=audiotool_dot_longrunning_dot_v1_dot_operation__pb2.CancelOperationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
