# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: audiotool/genre/v1/genre_service.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import audiotool.genre.v1.genre_service_pb2 as audiotool_dot_genre_dot_v1_dot_genre__service__pb2


class GenreService(Protocol):
    async def list_genres(self, request: audiotool_dot_genre_dot_v1_dot_genre__service__pb2.ListGenresRequest, ctx: RequestContext) -> audiotool_dot_genre_dot_v1_dot_genre__service__pb2.ListGenresResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_genre(self, request: audiotool_dot_genre_dot_v1_dot_genre__service__pb2.GetGenreRequest, ctx: RequestContext) -> audiotool_dot_genre_dot_v1_dot_genre__service__pb2.GetGenreResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class GenreServiceASGIApplication(ConnectASGIApplication[GenreService]):
    def __init__(self, service: GenreService | AsyncGenerator[GenreService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/audiotool.genre.v1.GenreService/ListGenres": Endpoint.unary(
                    method=MethodInfo(
                        name="ListGenres",
                        service_name="audiotool.genre.v1.GenreService",
                        input=audiotool_dot_genre_dot_v1_dot_genre__service__pb2.ListGenresRequest,
                        output=audiotool_dot_genre_dot_v1_dot_genre__service__pb2.ListGenresResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_genres,
                ),
                "/audiotool.genre.v1.GenreService/GetGenre": Endpoint.unary(
                    method=MethodInfo(
                        name="GetGenre",
                        service_name="audiotool.genre.v1.GenreService",
                        input=audiotool_dot_genre_dot_v1_dot_genre__service__pb2.GetGenreRequest,
                        output=audiotool_dot_genre_dot_v1_dot_genre__service__pb2.GetGenreResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_genre,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/audiotool.genre.v1.GenreService"


class GenreServiceClient(ConnectClient):
    async def list_genres(
        self,
        request: audiotool_dot_genre_dot_v1_dot_genre__service__pb2.ListGenresRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_genre_dot_v1_dot_genre__service__pb2.ListGenresResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListGenres",
                service_name="audiotool.genre.v1.GenreService",
                input=audiotool_dot_genre_dot_v1_dot_genre__service__pb2.ListGenresRequest,
                output=audiotool_dot_genre_dot_v1_dot_genre__service__pb2.ListGenresResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_genre(
        self,
        request: audiotool_dot_genre_dot_v1_dot_genre__service__pb2.GetGenreRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_genre_dot_v1_dot_genre__service__pb2.GetGenreResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetGenre",
                service_name="audiotool.genre.v1.GenreService",
                input=audiotool_dot_genre_dot_v1_dot_genre__service__pb2.GetGenreRequest,
                output=audiotool_dot_genre_dot_v1_dot_genre__service__pb2.GetGenreResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class GenreServiceSync(Protocol):
    def list_genres(self, request: audiotool_dot_genre_dot_v1_dot_genre__service__pb2.ListGenresRequest, ctx: RequestContext) -> audiotool_dot_genre_dot_v1_dot_genre__service__pb2.ListGenresResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_genre(self, request: audiotool_dot_genre_dot_v1_dot_genre__service__pb2.GetGenreRequest, ctx: RequestContext) -> audiotool_dot_genre_dot_v1_dot_genre__service__pb2.GetGenreResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class GenreServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: GenreServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/audiotool.genre.v1.GenreService/ListGenres": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListGenres",
                        service_name="audiotool.genre.v1.GenreService",
                        input=audiotool_dot_genre_dot_v1_dot_genre__service__pb2.ListGenresRequest,
                        output=audiotool_dot_genre_dot_v1_dot_genre__service__pb2.ListGenresResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_genres,
                ),
                "/audiotool.genre.v1.GenreService/GetGenre": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetGenre",
                        service_name="audiotool.genre.v1.GenreService",
                        input=audiotool_dot_genre_dot_v1_dot_genre__service__pb2.GetGenreRequest,
                        output=audiotool_dot_genre_dot_v1_dot_genre__service__pb2.GetGenreResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_genre,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/audiotool.genre.v1.GenreService"


class GenreServiceClientSync(ConnectClientSync):
    def list_genres(
        self,
        request: audiotool_dot_genre_dot_v1_dot_genre__service__pb2.ListGenresRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_genre_dot_v1_dot_genre__service__pb2.ListGenresResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListGenres",
                service_name="audiotool.genre.v1.GenreService",
                input=audiotool_dot_genre_dot_v1_dot_genre__service__pb2.ListGenresRequest,
                output=audiotool_dot_genre_dot_v1_dot_genre__service__pb2.ListGenresResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_genre(
        self,
        request: audiotool_dot_genre_dot_v1_dot_genre__service__pb2.GetGenreRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_genre_dot_v1_dot_genre__service__pb2.GetGenreResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetGenre",
                service_name="audiotool.genre.v1.GenreService",
                input=audiotool_dot_genre_dot_v1_dot_genre__service__pb2.GetGenreRequest,
                output=audiotool_dot_genre_dot_v1_dot_genre__service__pb2.GetGenreResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
