# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audiotool/genre/v1/genre_service.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'audiotool/genre/v1/genre_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from audiotool.genre.v1 import genre_pb2 as audiotool_dot_genre_dot_v1_dot_genre__pb2
from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from google.api import resource_pb2 as google_dot_api_dot_resource__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&audiotool/genre/v1/genre_service.proto\x12\x12\x61udiotool.genre.v1\x1a\x1e\x61udiotool/genre/v1/genre.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\"\x82\x01\n\x11ListGenresRequest\x12\x16\n\x06\x66ilter\x18\x01 \x01(\tR\x06\x66ilter\x12\x1b\n\tpage_size\x18\x02 \x01(\x05R\x08pageSize\x12\x1d\n\npage_token\x18\x03 \x01(\tR\tpageToken\x12\x19\n\x08order_by\x18\x04 \x01(\tR\x07orderBy\"o\n\x12ListGenresResponse\x12\x31\n\x06genres\x18\x01 \x03(\x0b\x32\x19.audiotool.genre.v1.GenreR\x06genres\x12&\n\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"L\n\x0fGetGenreRequest\x12\x39\n\x04name\x18\x01 \x01(\tB%\xe0\x41\x02\xfa\x41\x1f\n\x1dgenre.api.audiotool.com/GenreR\x04name\"C\n\x10GetGenreResponse\x12/\n\x05genre\x18\x01 \x01(\x0b\x32\x19.audiotool.genre.v1.GenreR\x05genre2\xc6\x01\n\x0cGenreService\x12]\n\nListGenres\x12%.audiotool.genre.v1.ListGenresRequest\x1a&.audiotool.genre.v1.ListGenresResponse\"\x00\x12W\n\x08GetGenre\x12#.audiotool.genre.v1.GetGenreRequest\x1a$.audiotool.genre.v1.GetGenreResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audiotool.genre.v1.genre_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETGENREREQUEST'].fields_by_name['name']._loaded_options = None
  _globals['_GETGENREREQUEST'].fields_by_name['name']._serialized_options = b'\340A\002\372A\037\n\035genre.api.audiotool.com/Genre'
  _globals['_LISTGENRESREQUEST']._serialized_start=155
  _globals['_LISTGENRESREQUEST']._serialized_end=285
  _globals['_LISTGENRESRESPONSE']._serialized_start=287
  _globals['_LISTGENRESRESPONSE']._serialized_end=398
  _globals['_GETGENREREQUEST']._serialized_start=400
  _globals['_GETGENREREQUEST']._serialized_end=476
  _globals['_GETGENRERESPONSE']._serialized_start=478
  _globals['_GETGENRERESPONSE']._serialized_end=545
  _globals['_GENRESERVICE']._serialized_start=548
  _globals['_GENRESERVICE']._serialized_end=746
# @@protoc_insertion_point(module_scope)
