# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: audiotool/projecttemplate/v1/project_template_service.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import audiotool.projecttemplate.v1.project_template_service_pb2 as audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2


class ProjectTemplateService(Protocol):
    async def list_project_template_templates(self, request: audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.ListProjectTemplatesRequest, ctx: RequestContext) -> audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.ListProjectTemplatesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_project_template_template(self, request: audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.GetProjectTemplateRequest, ctx: RequestContext) -> audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.GetProjectTemplateResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def create_project_template(self, request: audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.CreateProjectTemplateRequest, ctx: RequestContext) -> audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.CreateProjectTemplateResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def update_project_template(self, request: audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.UpdateProjectTemplateRequest, ctx: RequestContext) -> audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.UpdateProjectTemplateResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_project_template(self, request: audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.DeleteProjectTemplateRequest, ctx: RequestContext) -> audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.DeleteProjectTemplateResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class ProjectTemplateServiceASGIApplication(ConnectASGIApplication[ProjectTemplateService]):
    def __init__(self, service: ProjectTemplateService | AsyncGenerator[ProjectTemplateService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/audiotool.projecttemplate.v1.ProjectTemplateService/ListProjectTemplateTemplates": Endpoint.unary(
                    method=MethodInfo(
                        name="ListProjectTemplateTemplates",
                        service_name="audiotool.projecttemplate.v1.ProjectTemplateService",
                        input=audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.ListProjectTemplatesRequest,
                        output=audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.ListProjectTemplatesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_project_template_templates,
                ),
                "/audiotool.projecttemplate.v1.ProjectTemplateService/GetProjectTemplateTemplate": Endpoint.unary(
                    method=MethodInfo(
                        name="GetProjectTemplateTemplate",
                        service_name="audiotool.projecttemplate.v1.ProjectTemplateService",
                        input=audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.GetProjectTemplateRequest,
                        output=audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.GetProjectTemplateResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_project_template_template,
                ),
                "/audiotool.projecttemplate.v1.ProjectTemplateService/CreateProjectTemplate": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateProjectTemplate",
                        service_name="audiotool.projecttemplate.v1.ProjectTemplateService",
                        input=audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.CreateProjectTemplateRequest,
                        output=audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.CreateProjectTemplateResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_project_template,
                ),
                "/audiotool.projecttemplate.v1.ProjectTemplateService/UpdateProjectTemplate": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateProjectTemplate",
                        service_name="audiotool.projecttemplate.v1.ProjectTemplateService",
                        input=audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.UpdateProjectTemplateRequest,
                        output=audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.UpdateProjectTemplateResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.update_project_template,
                ),
                "/audiotool.projecttemplate.v1.ProjectTemplateService/DeleteProjectTemplate": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteProjectTemplate",
                        service_name="audiotool.projecttemplate.v1.ProjectTemplateService",
                        input=audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.DeleteProjectTemplateRequest,
                        output=audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.DeleteProjectTemplateResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_project_template,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/audiotool.projecttemplate.v1.ProjectTemplateService"


class ProjectTemplateServiceClient(ConnectClient):
    async def list_project_template_templates(
        self,
        request: audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.ListProjectTemplatesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.ListProjectTemplatesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListProjectTemplateTemplates",
                service_name="audiotool.projecttemplate.v1.ProjectTemplateService",
                input=audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.ListProjectTemplatesRequest,
                output=audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.ListProjectTemplatesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_project_template_template(
        self,
        request: audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.GetProjectTemplateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.GetProjectTemplateResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetProjectTemplateTemplate",
                service_name="audiotool.projecttemplate.v1.ProjectTemplateService",
                input=audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.GetProjectTemplateRequest,
                output=audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.GetProjectTemplateResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def create_project_template(
        self,
        request: audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.CreateProjectTemplateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.CreateProjectTemplateResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateProjectTemplate",
                service_name="audiotool.projecttemplate.v1.ProjectTemplateService",
                input=audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.CreateProjectTemplateRequest,
                output=audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.CreateProjectTemplateResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_project_template(
        self,
        request: audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.UpdateProjectTemplateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.UpdateProjectTemplateResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateProjectTemplate",
                service_name="audiotool.projecttemplate.v1.ProjectTemplateService",
                input=audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.UpdateProjectTemplateRequest,
                output=audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.UpdateProjectTemplateResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_project_template(
        self,
        request: audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.DeleteProjectTemplateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.DeleteProjectTemplateResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteProjectTemplate",
                service_name="audiotool.projecttemplate.v1.ProjectTemplateService",
                input=audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.DeleteProjectTemplateRequest,
                output=audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.DeleteProjectTemplateResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class ProjectTemplateServiceSync(Protocol):
    def list_project_template_templates(self, request: audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.ListProjectTemplatesRequest, ctx: RequestContext) -> audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.ListProjectTemplatesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_project_template_template(self, request: audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.GetProjectTemplateRequest, ctx: RequestContext) -> audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.GetProjectTemplateResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def create_project_template(self, request: audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.CreateProjectTemplateRequest, ctx: RequestContext) -> audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.CreateProjectTemplateResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def update_project_template(self, request: audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.UpdateProjectTemplateRequest, ctx: RequestContext) -> audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.UpdateProjectTemplateResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_project_template(self, request: audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.DeleteProjectTemplateRequest, ctx: RequestContext) -> audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.DeleteProjectTemplateResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class ProjectTemplateServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: ProjectTemplateServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/audiotool.projecttemplate.v1.ProjectTemplateService/ListProjectTemplateTemplates": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListProjectTemplateTemplates",
                        service_name="audiotool.projecttemplate.v1.ProjectTemplateService",
                        input=audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.ListProjectTemplatesRequest,
                        output=audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.ListProjectTemplatesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_project_template_templates,
                ),
                "/audiotool.projecttemplate.v1.ProjectTemplateService/GetProjectTemplateTemplate": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetProjectTemplateTemplate",
                        service_name="audiotool.projecttemplate.v1.ProjectTemplateService",
                        input=audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.GetProjectTemplateRequest,
                        output=audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.GetProjectTemplateResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_project_template_template,
                ),
                "/audiotool.projecttemplate.v1.ProjectTemplateService/CreateProjectTemplate": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateProjectTemplate",
                        service_name="audiotool.projecttemplate.v1.ProjectTemplateService",
                        input=audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.CreateProjectTemplateRequest,
                        output=audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.CreateProjectTemplateResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_project_template,
                ),
                "/audiotool.projecttemplate.v1.ProjectTemplateService/UpdateProjectTemplate": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateProjectTemplate",
                        service_name="audiotool.projecttemplate.v1.ProjectTemplateService",
                        input=audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.UpdateProjectTemplateRequest,
                        output=audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.UpdateProjectTemplateResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_project_template,
                ),
                "/audiotool.projecttemplate.v1.ProjectTemplateService/DeleteProjectTemplate": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteProjectTemplate",
                        service_name="audiotool.projecttemplate.v1.ProjectTemplateService",
                        input=audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.DeleteProjectTemplateRequest,
                        output=audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.DeleteProjectTemplateResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_project_template,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/audiotool.projecttemplate.v1.ProjectTemplateService"


class ProjectTemplateServiceClientSync(ConnectClientSync):
    def list_project_template_templates(
        self,
        request: audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.ListProjectTemplatesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.ListProjectTemplatesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListProjectTemplateTemplates",
                service_name="audiotool.projecttemplate.v1.ProjectTemplateService",
                input=audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.ListProjectTemplatesRequest,
                output=audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.ListProjectTemplatesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_project_template_template(
        self,
        request: audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.GetProjectTemplateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.GetProjectTemplateResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetProjectTemplateTemplate",
                service_name="audiotool.projecttemplate.v1.ProjectTemplateService",
                input=audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.GetProjectTemplateRequest,
                output=audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.GetProjectTemplateResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def create_project_template(
        self,
        request: audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.CreateProjectTemplateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.CreateProjectTemplateResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateProjectTemplate",
                service_name="audiotool.projecttemplate.v1.ProjectTemplateService",
                input=audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.CreateProjectTemplateRequest,
                output=audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.CreateProjectTemplateResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def update_project_template(
        self,
        request: audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.UpdateProjectTemplateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.UpdateProjectTemplateResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateProjectTemplate",
                service_name="audiotool.projecttemplate.v1.ProjectTemplateService",
                input=audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.UpdateProjectTemplateRequest,
                output=audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.UpdateProjectTemplateResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_project_template(
        self,
        request: audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.DeleteProjectTemplateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.DeleteProjectTemplateResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteProjectTemplate",
                service_name="audiotool.projecttemplate.v1.ProjectTemplateService",
                input=audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.DeleteProjectTemplateRequest,
                output=audiotool_dot_projecttemplate_dot_v1_dot_project__template__service__pb2.DeleteProjectTemplateResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
