# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: audiotool/track/v1/track_service.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import audiotool.track.v1.track_service_pb2 as audiotool_dot_track_dot_v1_dot_track__service__pb2


class TrackService(Protocol):
    async def list_tracks(self, request: audiotool_dot_track_dot_v1_dot_track__service__pb2.ListTracksRequest, ctx: RequestContext) -> audiotool_dot_track_dot_v1_dot_track__service__pb2.ListTracksResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_track(self, request: audiotool_dot_track_dot_v1_dot_track__service__pb2.GetTrackRequest, ctx: RequestContext) -> audiotool_dot_track_dot_v1_dot_track__service__pb2.GetTrackResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_track(self, request: audiotool_dot_track_dot_v1_dot_track__service__pb2.DeleteTrackRequest, ctx: RequestContext) -> audiotool_dot_track_dot_v1_dot_track__service__pb2.DeleteTrackResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_track_listen_by_user(self, request: audiotool_dot_track_dot_v1_dot_track__service__pb2.ListTrackListenByUserRequest, ctx: RequestContext) -> audiotool_dot_track_dot_v1_dot_track__service__pb2.ListTrackListenByUserResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class TrackServiceASGIApplication(ConnectASGIApplication[TrackService]):
    def __init__(self, service: TrackService | AsyncGenerator[TrackService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/audiotool.track.v1.TrackService/ListTracks": Endpoint.unary(
                    method=MethodInfo(
                        name="ListTracks",
                        service_name="audiotool.track.v1.TrackService",
                        input=audiotool_dot_track_dot_v1_dot_track__service__pb2.ListTracksRequest,
                        output=audiotool_dot_track_dot_v1_dot_track__service__pb2.ListTracksResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_tracks,
                ),
                "/audiotool.track.v1.TrackService/GetTrack": Endpoint.unary(
                    method=MethodInfo(
                        name="GetTrack",
                        service_name="audiotool.track.v1.TrackService",
                        input=audiotool_dot_track_dot_v1_dot_track__service__pb2.GetTrackRequest,
                        output=audiotool_dot_track_dot_v1_dot_track__service__pb2.GetTrackResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_track,
                ),
                "/audiotool.track.v1.TrackService/DeleteTrack": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteTrack",
                        service_name="audiotool.track.v1.TrackService",
                        input=audiotool_dot_track_dot_v1_dot_track__service__pb2.DeleteTrackRequest,
                        output=audiotool_dot_track_dot_v1_dot_track__service__pb2.DeleteTrackResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_track,
                ),
                "/audiotool.track.v1.TrackService/ListTrackListenByUser": Endpoint.unary(
                    method=MethodInfo(
                        name="ListTrackListenByUser",
                        service_name="audiotool.track.v1.TrackService",
                        input=audiotool_dot_track_dot_v1_dot_track__service__pb2.ListTrackListenByUserRequest,
                        output=audiotool_dot_track_dot_v1_dot_track__service__pb2.ListTrackListenByUserResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_track_listen_by_user,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/audiotool.track.v1.TrackService"


class TrackServiceClient(ConnectClient):
    async def list_tracks(
        self,
        request: audiotool_dot_track_dot_v1_dot_track__service__pb2.ListTracksRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_track_dot_v1_dot_track__service__pb2.ListTracksResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListTracks",
                service_name="audiotool.track.v1.TrackService",
                input=audiotool_dot_track_dot_v1_dot_track__service__pb2.ListTracksRequest,
                output=audiotool_dot_track_dot_v1_dot_track__service__pb2.ListTracksResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_track(
        self,
        request: audiotool_dot_track_dot_v1_dot_track__service__pb2.GetTrackRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_track_dot_v1_dot_track__service__pb2.GetTrackResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetTrack",
                service_name="audiotool.track.v1.TrackService",
                input=audiotool_dot_track_dot_v1_dot_track__service__pb2.GetTrackRequest,
                output=audiotool_dot_track_dot_v1_dot_track__service__pb2.GetTrackResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_track(
        self,
        request: audiotool_dot_track_dot_v1_dot_track__service__pb2.DeleteTrackRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_track_dot_v1_dot_track__service__pb2.DeleteTrackResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteTrack",
                service_name="audiotool.track.v1.TrackService",
                input=audiotool_dot_track_dot_v1_dot_track__service__pb2.DeleteTrackRequest,
                output=audiotool_dot_track_dot_v1_dot_track__service__pb2.DeleteTrackResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_track_listen_by_user(
        self,
        request: audiotool_dot_track_dot_v1_dot_track__service__pb2.ListTrackListenByUserRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_track_dot_v1_dot_track__service__pb2.ListTrackListenByUserResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListTrackListenByUser",
                service_name="audiotool.track.v1.TrackService",
                input=audiotool_dot_track_dot_v1_dot_track__service__pb2.ListTrackListenByUserRequest,
                output=audiotool_dot_track_dot_v1_dot_track__service__pb2.ListTrackListenByUserResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class TrackServiceSync(Protocol):
    def list_tracks(self, request: audiotool_dot_track_dot_v1_dot_track__service__pb2.ListTracksRequest, ctx: RequestContext) -> audiotool_dot_track_dot_v1_dot_track__service__pb2.ListTracksResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_track(self, request: audiotool_dot_track_dot_v1_dot_track__service__pb2.GetTrackRequest, ctx: RequestContext) -> audiotool_dot_track_dot_v1_dot_track__service__pb2.GetTrackResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_track(self, request: audiotool_dot_track_dot_v1_dot_track__service__pb2.DeleteTrackRequest, ctx: RequestContext) -> audiotool_dot_track_dot_v1_dot_track__service__pb2.DeleteTrackResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_track_listen_by_user(self, request: audiotool_dot_track_dot_v1_dot_track__service__pb2.ListTrackListenByUserRequest, ctx: RequestContext) -> audiotool_dot_track_dot_v1_dot_track__service__pb2.ListTrackListenByUserResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class TrackServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: TrackServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/audiotool.track.v1.TrackService/ListTracks": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListTracks",
                        service_name="audiotool.track.v1.TrackService",
                        input=audiotool_dot_track_dot_v1_dot_track__service__pb2.ListTracksRequest,
                        output=audiotool_dot_track_dot_v1_dot_track__service__pb2.ListTracksResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_tracks,
                ),
                "/audiotool.track.v1.TrackService/GetTrack": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetTrack",
                        service_name="audiotool.track.v1.TrackService",
                        input=audiotool_dot_track_dot_v1_dot_track__service__pb2.GetTrackRequest,
                        output=audiotool_dot_track_dot_v1_dot_track__service__pb2.GetTrackResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_track,
                ),
                "/audiotool.track.v1.TrackService/DeleteTrack": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteTrack",
                        service_name="audiotool.track.v1.TrackService",
                        input=audiotool_dot_track_dot_v1_dot_track__service__pb2.DeleteTrackRequest,
                        output=audiotool_dot_track_dot_v1_dot_track__service__pb2.DeleteTrackResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_track,
                ),
                "/audiotool.track.v1.TrackService/ListTrackListenByUser": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListTrackListenByUser",
                        service_name="audiotool.track.v1.TrackService",
                        input=audiotool_dot_track_dot_v1_dot_track__service__pb2.ListTrackListenByUserRequest,
                        output=audiotool_dot_track_dot_v1_dot_track__service__pb2.ListTrackListenByUserResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_track_listen_by_user,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/audiotool.track.v1.TrackService"


class TrackServiceClientSync(ConnectClientSync):
    def list_tracks(
        self,
        request: audiotool_dot_track_dot_v1_dot_track__service__pb2.ListTracksRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_track_dot_v1_dot_track__service__pb2.ListTracksResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListTracks",
                service_name="audiotool.track.v1.TrackService",
                input=audiotool_dot_track_dot_v1_dot_track__service__pb2.ListTracksRequest,
                output=audiotool_dot_track_dot_v1_dot_track__service__pb2.ListTracksResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_track(
        self,
        request: audiotool_dot_track_dot_v1_dot_track__service__pb2.GetTrackRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_track_dot_v1_dot_track__service__pb2.GetTrackResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetTrack",
                service_name="audiotool.track.v1.TrackService",
                input=audiotool_dot_track_dot_v1_dot_track__service__pb2.GetTrackRequest,
                output=audiotool_dot_track_dot_v1_dot_track__service__pb2.GetTrackResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_track(
        self,
        request: audiotool_dot_track_dot_v1_dot_track__service__pb2.DeleteTrackRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_track_dot_v1_dot_track__service__pb2.DeleteTrackResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteTrack",
                service_name="audiotool.track.v1.TrackService",
                input=audiotool_dot_track_dot_v1_dot_track__service__pb2.DeleteTrackRequest,
                output=audiotool_dot_track_dot_v1_dot_track__service__pb2.DeleteTrackResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_track_listen_by_user(
        self,
        request: audiotool_dot_track_dot_v1_dot_track__service__pb2.ListTrackListenByUserRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_track_dot_v1_dot_track__service__pb2.ListTrackListenByUserResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListTrackListenByUser",
                service_name="audiotool.track.v1.TrackService",
                input=audiotool_dot_track_dot_v1_dot_track__service__pb2.ListTrackListenByUserRequest,
                output=audiotool_dot_track_dot_v1_dot_track__service__pb2.ListTrackListenByUserResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
