# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: audiotool/project/v1/project_service.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import audiotool.longrunning.v1.operation_pb2 as audiotool_dot_longrunning_dot_v1_dot_operation__pb2
import audiotool.project.v1.project_service_pb2 as audiotool_dot_project_dot_v1_dot_project__service__pb2


class ProjectService(Protocol):
    async def list_projects(self, request: audiotool_dot_project_dot_v1_dot_project__service__pb2.ListProjectsRequest, ctx: RequestContext) -> audiotool_dot_project_dot_v1_dot_project__service__pb2.ListProjectsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_project(self, request: audiotool_dot_project_dot_v1_dot_project__service__pb2.GetProjectRequest, ctx: RequestContext) -> audiotool_dot_project_dot_v1_dot_project__service__pb2.GetProjectResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def create_project(self, request: audiotool_dot_project_dot_v1_dot_project__service__pb2.CreateProjectRequest, ctx: RequestContext) -> audiotool_dot_project_dot_v1_dot_project__service__pb2.CreateProjectResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def upload_cover(self, request: audiotool_dot_project_dot_v1_dot_project__service__pb2.UploadCoverRequest, ctx: RequestContext) -> audiotool_dot_project_dot_v1_dot_project__service__pb2.UploadCoverResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def update_project(self, request: audiotool_dot_project_dot_v1_dot_project__service__pb2.UpdateProjectRequest, ctx: RequestContext) -> audiotool_dot_project_dot_v1_dot_project__service__pb2.UpdateProjectResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_project(self, request: audiotool_dot_project_dot_v1_dot_project__service__pb2.DeleteProjectRequest, ctx: RequestContext) -> audiotool_dot_project_dot_v1_dot_project__service__pb2.DeleteProjectResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def sync_track(self, request: audiotool_dot_project_dot_v1_dot_project__service__pb2.SyncTrackRequest, ctx: RequestContext) -> audiotool_dot_longrunning_dot_v1_dot_operation__pb2.Operation:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def open_session(self, request: audiotool_dot_project_dot_v1_dot_project__service__pb2.OpenSessionRequest, ctx: RequestContext) -> audiotool_dot_project_dot_v1_dot_project__service__pb2.OpenSessionResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_sessions(self, request: audiotool_dot_project_dot_v1_dot_project__service__pb2.ListSessionsRequest, ctx: RequestContext) -> audiotool_dot_project_dot_v1_dot_project__service__pb2.ListSessionsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_latest_version_bundle(self, request: audiotool_dot_project_dot_v1_dot_project__service__pb2.GetLatestVersionBundleRequest, ctx: RequestContext) -> audiotool_dot_project_dot_v1_dot_project__service__pb2.GetLatestVersionBundleResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class ProjectServiceASGIApplication(ConnectASGIApplication[ProjectService]):
    def __init__(self, service: ProjectService | AsyncGenerator[ProjectService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/audiotool.project.v1.ProjectService/ListProjects": Endpoint.unary(
                    method=MethodInfo(
                        name="ListProjects",
                        service_name="audiotool.project.v1.ProjectService",
                        input=audiotool_dot_project_dot_v1_dot_project__service__pb2.ListProjectsRequest,
                        output=audiotool_dot_project_dot_v1_dot_project__service__pb2.ListProjectsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_projects,
                ),
                "/audiotool.project.v1.ProjectService/GetProject": Endpoint.unary(
                    method=MethodInfo(
                        name="GetProject",
                        service_name="audiotool.project.v1.ProjectService",
                        input=audiotool_dot_project_dot_v1_dot_project__service__pb2.GetProjectRequest,
                        output=audiotool_dot_project_dot_v1_dot_project__service__pb2.GetProjectResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_project,
                ),
                "/audiotool.project.v1.ProjectService/CreateProject": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateProject",
                        service_name="audiotool.project.v1.ProjectService",
                        input=audiotool_dot_project_dot_v1_dot_project__service__pb2.CreateProjectRequest,
                        output=audiotool_dot_project_dot_v1_dot_project__service__pb2.CreateProjectResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_project,
                ),
                "/audiotool.project.v1.ProjectService/UploadCover": Endpoint.unary(
                    method=MethodInfo(
                        name="UploadCover",
                        service_name="audiotool.project.v1.ProjectService",
                        input=audiotool_dot_project_dot_v1_dot_project__service__pb2.UploadCoverRequest,
                        output=audiotool_dot_project_dot_v1_dot_project__service__pb2.UploadCoverResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.upload_cover,
                ),
                "/audiotool.project.v1.ProjectService/UpdateProject": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateProject",
                        service_name="audiotool.project.v1.ProjectService",
                        input=audiotool_dot_project_dot_v1_dot_project__service__pb2.UpdateProjectRequest,
                        output=audiotool_dot_project_dot_v1_dot_project__service__pb2.UpdateProjectResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.update_project,
                ),
                "/audiotool.project.v1.ProjectService/DeleteProject": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteProject",
                        service_name="audiotool.project.v1.ProjectService",
                        input=audiotool_dot_project_dot_v1_dot_project__service__pb2.DeleteProjectRequest,
                        output=audiotool_dot_project_dot_v1_dot_project__service__pb2.DeleteProjectResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_project,
                ),
                "/audiotool.project.v1.ProjectService/SyncTrack": Endpoint.unary(
                    method=MethodInfo(
                        name="SyncTrack",
                        service_name="audiotool.project.v1.ProjectService",
                        input=audiotool_dot_project_dot_v1_dot_project__service__pb2.SyncTrackRequest,
                        output=audiotool_dot_longrunning_dot_v1_dot_operation__pb2.Operation,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.sync_track,
                ),
                "/audiotool.project.v1.ProjectService/OpenSession": Endpoint.unary(
                    method=MethodInfo(
                        name="OpenSession",
                        service_name="audiotool.project.v1.ProjectService",
                        input=audiotool_dot_project_dot_v1_dot_project__service__pb2.OpenSessionRequest,
                        output=audiotool_dot_project_dot_v1_dot_project__service__pb2.OpenSessionResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.open_session,
                ),
                "/audiotool.project.v1.ProjectService/ListSessions": Endpoint.unary(
                    method=MethodInfo(
                        name="ListSessions",
                        service_name="audiotool.project.v1.ProjectService",
                        input=audiotool_dot_project_dot_v1_dot_project__service__pb2.ListSessionsRequest,
                        output=audiotool_dot_project_dot_v1_dot_project__service__pb2.ListSessionsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_sessions,
                ),
                "/audiotool.project.v1.ProjectService/GetLatestVersionBundle": Endpoint.unary(
                    method=MethodInfo(
                        name="GetLatestVersionBundle",
                        service_name="audiotool.project.v1.ProjectService",
                        input=audiotool_dot_project_dot_v1_dot_project__service__pb2.GetLatestVersionBundleRequest,
                        output=audiotool_dot_project_dot_v1_dot_project__service__pb2.GetLatestVersionBundleResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_latest_version_bundle,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/audiotool.project.v1.ProjectService"


class ProjectServiceClient(ConnectClient):
    async def list_projects(
        self,
        request: audiotool_dot_project_dot_v1_dot_project__service__pb2.ListProjectsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_project_dot_v1_dot_project__service__pb2.ListProjectsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListProjects",
                service_name="audiotool.project.v1.ProjectService",
                input=audiotool_dot_project_dot_v1_dot_project__service__pb2.ListProjectsRequest,
                output=audiotool_dot_project_dot_v1_dot_project__service__pb2.ListProjectsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_project(
        self,
        request: audiotool_dot_project_dot_v1_dot_project__service__pb2.GetProjectRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_project_dot_v1_dot_project__service__pb2.GetProjectResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetProject",
                service_name="audiotool.project.v1.ProjectService",
                input=audiotool_dot_project_dot_v1_dot_project__service__pb2.GetProjectRequest,
                output=audiotool_dot_project_dot_v1_dot_project__service__pb2.GetProjectResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def create_project(
        self,
        request: audiotool_dot_project_dot_v1_dot_project__service__pb2.CreateProjectRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_project_dot_v1_dot_project__service__pb2.CreateProjectResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateProject",
                service_name="audiotool.project.v1.ProjectService",
                input=audiotool_dot_project_dot_v1_dot_project__service__pb2.CreateProjectRequest,
                output=audiotool_dot_project_dot_v1_dot_project__service__pb2.CreateProjectResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def upload_cover(
        self,
        request: audiotool_dot_project_dot_v1_dot_project__service__pb2.UploadCoverRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_project_dot_v1_dot_project__service__pb2.UploadCoverResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UploadCover",
                service_name="audiotool.project.v1.ProjectService",
                input=audiotool_dot_project_dot_v1_dot_project__service__pb2.UploadCoverRequest,
                output=audiotool_dot_project_dot_v1_dot_project__service__pb2.UploadCoverResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_project(
        self,
        request: audiotool_dot_project_dot_v1_dot_project__service__pb2.UpdateProjectRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_project_dot_v1_dot_project__service__pb2.UpdateProjectResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateProject",
                service_name="audiotool.project.v1.ProjectService",
                input=audiotool_dot_project_dot_v1_dot_project__service__pb2.UpdateProjectRequest,
                output=audiotool_dot_project_dot_v1_dot_project__service__pb2.UpdateProjectResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_project(
        self,
        request: audiotool_dot_project_dot_v1_dot_project__service__pb2.DeleteProjectRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_project_dot_v1_dot_project__service__pb2.DeleteProjectResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteProject",
                service_name="audiotool.project.v1.ProjectService",
                input=audiotool_dot_project_dot_v1_dot_project__service__pb2.DeleteProjectRequest,
                output=audiotool_dot_project_dot_v1_dot_project__service__pb2.DeleteProjectResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def sync_track(
        self,
        request: audiotool_dot_project_dot_v1_dot_project__service__pb2.SyncTrackRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_longrunning_dot_v1_dot_operation__pb2.Operation:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SyncTrack",
                service_name="audiotool.project.v1.ProjectService",
                input=audiotool_dot_project_dot_v1_dot_project__service__pb2.SyncTrackRequest,
                output=audiotool_dot_longrunning_dot_v1_dot_operation__pb2.Operation,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def open_session(
        self,
        request: audiotool_dot_project_dot_v1_dot_project__service__pb2.OpenSessionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_project_dot_v1_dot_project__service__pb2.OpenSessionResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="OpenSession",
                service_name="audiotool.project.v1.ProjectService",
                input=audiotool_dot_project_dot_v1_dot_project__service__pb2.OpenSessionRequest,
                output=audiotool_dot_project_dot_v1_dot_project__service__pb2.OpenSessionResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_sessions(
        self,
        request: audiotool_dot_project_dot_v1_dot_project__service__pb2.ListSessionsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_project_dot_v1_dot_project__service__pb2.ListSessionsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListSessions",
                service_name="audiotool.project.v1.ProjectService",
                input=audiotool_dot_project_dot_v1_dot_project__service__pb2.ListSessionsRequest,
                output=audiotool_dot_project_dot_v1_dot_project__service__pb2.ListSessionsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_latest_version_bundle(
        self,
        request: audiotool_dot_project_dot_v1_dot_project__service__pb2.GetLatestVersionBundleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_project_dot_v1_dot_project__service__pb2.GetLatestVersionBundleResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetLatestVersionBundle",
                service_name="audiotool.project.v1.ProjectService",
                input=audiotool_dot_project_dot_v1_dot_project__service__pb2.GetLatestVersionBundleRequest,
                output=audiotool_dot_project_dot_v1_dot_project__service__pb2.GetLatestVersionBundleResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class ProjectServiceSync(Protocol):
    def list_projects(self, request: audiotool_dot_project_dot_v1_dot_project__service__pb2.ListProjectsRequest, ctx: RequestContext) -> audiotool_dot_project_dot_v1_dot_project__service__pb2.ListProjectsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_project(self, request: audiotool_dot_project_dot_v1_dot_project__service__pb2.GetProjectRequest, ctx: RequestContext) -> audiotool_dot_project_dot_v1_dot_project__service__pb2.GetProjectResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def create_project(self, request: audiotool_dot_project_dot_v1_dot_project__service__pb2.CreateProjectRequest, ctx: RequestContext) -> audiotool_dot_project_dot_v1_dot_project__service__pb2.CreateProjectResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def upload_cover(self, request: audiotool_dot_project_dot_v1_dot_project__service__pb2.UploadCoverRequest, ctx: RequestContext) -> audiotool_dot_project_dot_v1_dot_project__service__pb2.UploadCoverResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def update_project(self, request: audiotool_dot_project_dot_v1_dot_project__service__pb2.UpdateProjectRequest, ctx: RequestContext) -> audiotool_dot_project_dot_v1_dot_project__service__pb2.UpdateProjectResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_project(self, request: audiotool_dot_project_dot_v1_dot_project__service__pb2.DeleteProjectRequest, ctx: RequestContext) -> audiotool_dot_project_dot_v1_dot_project__service__pb2.DeleteProjectResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def sync_track(self, request: audiotool_dot_project_dot_v1_dot_project__service__pb2.SyncTrackRequest, ctx: RequestContext) -> audiotool_dot_longrunning_dot_v1_dot_operation__pb2.Operation:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def open_session(self, request: audiotool_dot_project_dot_v1_dot_project__service__pb2.OpenSessionRequest, ctx: RequestContext) -> audiotool_dot_project_dot_v1_dot_project__service__pb2.OpenSessionResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_sessions(self, request: audiotool_dot_project_dot_v1_dot_project__service__pb2.ListSessionsRequest, ctx: RequestContext) -> audiotool_dot_project_dot_v1_dot_project__service__pb2.ListSessionsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_latest_version_bundle(self, request: audiotool_dot_project_dot_v1_dot_project__service__pb2.GetLatestVersionBundleRequest, ctx: RequestContext) -> audiotool_dot_project_dot_v1_dot_project__service__pb2.GetLatestVersionBundleResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class ProjectServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: ProjectServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/audiotool.project.v1.ProjectService/ListProjects": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListProjects",
                        service_name="audiotool.project.v1.ProjectService",
                        input=audiotool_dot_project_dot_v1_dot_project__service__pb2.ListProjectsRequest,
                        output=audiotool_dot_project_dot_v1_dot_project__service__pb2.ListProjectsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_projects,
                ),
                "/audiotool.project.v1.ProjectService/GetProject": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetProject",
                        service_name="audiotool.project.v1.ProjectService",
                        input=audiotool_dot_project_dot_v1_dot_project__service__pb2.GetProjectRequest,
                        output=audiotool_dot_project_dot_v1_dot_project__service__pb2.GetProjectResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_project,
                ),
                "/audiotool.project.v1.ProjectService/CreateProject": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateProject",
                        service_name="audiotool.project.v1.ProjectService",
                        input=audiotool_dot_project_dot_v1_dot_project__service__pb2.CreateProjectRequest,
                        output=audiotool_dot_project_dot_v1_dot_project__service__pb2.CreateProjectResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_project,
                ),
                "/audiotool.project.v1.ProjectService/UploadCover": EndpointSync.unary(
                    method=MethodInfo(
                        name="UploadCover",
                        service_name="audiotool.project.v1.ProjectService",
                        input=audiotool_dot_project_dot_v1_dot_project__service__pb2.UploadCoverRequest,
                        output=audiotool_dot_project_dot_v1_dot_project__service__pb2.UploadCoverResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.upload_cover,
                ),
                "/audiotool.project.v1.ProjectService/UpdateProject": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateProject",
                        service_name="audiotool.project.v1.ProjectService",
                        input=audiotool_dot_project_dot_v1_dot_project__service__pb2.UpdateProjectRequest,
                        output=audiotool_dot_project_dot_v1_dot_project__service__pb2.UpdateProjectResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_project,
                ),
                "/audiotool.project.v1.ProjectService/DeleteProject": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteProject",
                        service_name="audiotool.project.v1.ProjectService",
                        input=audiotool_dot_project_dot_v1_dot_project__service__pb2.DeleteProjectRequest,
                        output=audiotool_dot_project_dot_v1_dot_project__service__pb2.DeleteProjectResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_project,
                ),
                "/audiotool.project.v1.ProjectService/SyncTrack": EndpointSync.unary(
                    method=MethodInfo(
                        name="SyncTrack",
                        service_name="audiotool.project.v1.ProjectService",
                        input=audiotool_dot_project_dot_v1_dot_project__service__pb2.SyncTrackRequest,
                        output=audiotool_dot_longrunning_dot_v1_dot_operation__pb2.Operation,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.sync_track,
                ),
                "/audiotool.project.v1.ProjectService/OpenSession": EndpointSync.unary(
                    method=MethodInfo(
                        name="OpenSession",
                        service_name="audiotool.project.v1.ProjectService",
                        input=audiotool_dot_project_dot_v1_dot_project__service__pb2.OpenSessionRequest,
                        output=audiotool_dot_project_dot_v1_dot_project__service__pb2.OpenSessionResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.open_session,
                ),
                "/audiotool.project.v1.ProjectService/ListSessions": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListSessions",
                        service_name="audiotool.project.v1.ProjectService",
                        input=audiotool_dot_project_dot_v1_dot_project__service__pb2.ListSessionsRequest,
                        output=audiotool_dot_project_dot_v1_dot_project__service__pb2.ListSessionsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_sessions,
                ),
                "/audiotool.project.v1.ProjectService/GetLatestVersionBundle": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetLatestVersionBundle",
                        service_name="audiotool.project.v1.ProjectService",
                        input=audiotool_dot_project_dot_v1_dot_project__service__pb2.GetLatestVersionBundleRequest,
                        output=audiotool_dot_project_dot_v1_dot_project__service__pb2.GetLatestVersionBundleResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_latest_version_bundle,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/audiotool.project.v1.ProjectService"


class ProjectServiceClientSync(ConnectClientSync):
    def list_projects(
        self,
        request: audiotool_dot_project_dot_v1_dot_project__service__pb2.ListProjectsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_project_dot_v1_dot_project__service__pb2.ListProjectsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListProjects",
                service_name="audiotool.project.v1.ProjectService",
                input=audiotool_dot_project_dot_v1_dot_project__service__pb2.ListProjectsRequest,
                output=audiotool_dot_project_dot_v1_dot_project__service__pb2.ListProjectsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_project(
        self,
        request: audiotool_dot_project_dot_v1_dot_project__service__pb2.GetProjectRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_project_dot_v1_dot_project__service__pb2.GetProjectResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetProject",
                service_name="audiotool.project.v1.ProjectService",
                input=audiotool_dot_project_dot_v1_dot_project__service__pb2.GetProjectRequest,
                output=audiotool_dot_project_dot_v1_dot_project__service__pb2.GetProjectResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def create_project(
        self,
        request: audiotool_dot_project_dot_v1_dot_project__service__pb2.CreateProjectRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_project_dot_v1_dot_project__service__pb2.CreateProjectResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateProject",
                service_name="audiotool.project.v1.ProjectService",
                input=audiotool_dot_project_dot_v1_dot_project__service__pb2.CreateProjectRequest,
                output=audiotool_dot_project_dot_v1_dot_project__service__pb2.CreateProjectResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def upload_cover(
        self,
        request: audiotool_dot_project_dot_v1_dot_project__service__pb2.UploadCoverRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_project_dot_v1_dot_project__service__pb2.UploadCoverResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UploadCover",
                service_name="audiotool.project.v1.ProjectService",
                input=audiotool_dot_project_dot_v1_dot_project__service__pb2.UploadCoverRequest,
                output=audiotool_dot_project_dot_v1_dot_project__service__pb2.UploadCoverResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def update_project(
        self,
        request: audiotool_dot_project_dot_v1_dot_project__service__pb2.UpdateProjectRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_project_dot_v1_dot_project__service__pb2.UpdateProjectResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateProject",
                service_name="audiotool.project.v1.ProjectService",
                input=audiotool_dot_project_dot_v1_dot_project__service__pb2.UpdateProjectRequest,
                output=audiotool_dot_project_dot_v1_dot_project__service__pb2.UpdateProjectResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_project(
        self,
        request: audiotool_dot_project_dot_v1_dot_project__service__pb2.DeleteProjectRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_project_dot_v1_dot_project__service__pb2.DeleteProjectResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteProject",
                service_name="audiotool.project.v1.ProjectService",
                input=audiotool_dot_project_dot_v1_dot_project__service__pb2.DeleteProjectRequest,
                output=audiotool_dot_project_dot_v1_dot_project__service__pb2.DeleteProjectResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def sync_track(
        self,
        request: audiotool_dot_project_dot_v1_dot_project__service__pb2.SyncTrackRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_longrunning_dot_v1_dot_operation__pb2.Operation:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SyncTrack",
                service_name="audiotool.project.v1.ProjectService",
                input=audiotool_dot_project_dot_v1_dot_project__service__pb2.SyncTrackRequest,
                output=audiotool_dot_longrunning_dot_v1_dot_operation__pb2.Operation,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def open_session(
        self,
        request: audiotool_dot_project_dot_v1_dot_project__service__pb2.OpenSessionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_project_dot_v1_dot_project__service__pb2.OpenSessionResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="OpenSession",
                service_name="audiotool.project.v1.ProjectService",
                input=audiotool_dot_project_dot_v1_dot_project__service__pb2.OpenSessionRequest,
                output=audiotool_dot_project_dot_v1_dot_project__service__pb2.OpenSessionResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_sessions(
        self,
        request: audiotool_dot_project_dot_v1_dot_project__service__pb2.ListSessionsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_project_dot_v1_dot_project__service__pb2.ListSessionsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListSessions",
                service_name="audiotool.project.v1.ProjectService",
                input=audiotool_dot_project_dot_v1_dot_project__service__pb2.ListSessionsRequest,
                output=audiotool_dot_project_dot_v1_dot_project__service__pb2.ListSessionsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_latest_version_bundle(
        self,
        request: audiotool_dot_project_dot_v1_dot_project__service__pb2.GetLatestVersionBundleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_project_dot_v1_dot_project__service__pb2.GetLatestVersionBundleResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetLatestVersionBundle",
                service_name="audiotool.project.v1.ProjectService",
                input=audiotool_dot_project_dot_v1_dot_project__service__pb2.GetLatestVersionBundleRequest,
                output=audiotool_dot_project_dot_v1_dot_project__service__pb2.GetLatestVersionBundleResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
