# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audiotool/project/v1/project_role.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'audiotool/project/v1/project_role.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'audiotool/project/v1/project_role.proto\x12\x14\x61udiotool.project.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x97\x03\n\x0bProjectRole\x12\x17\n\x04name\x18\x01 \x01(\tB\x03\xe0\x41\x08R\x04name\x12 \n\tuser_name\x18\x02 \x01(\tB\x03\xe0\x41\x02R\x08userName\x12G\n\trole_type\x18\x03 \x01(\x0e\x32%.audiotool.project.v1.ProjectRoleTypeB\x03\xe0\x41\x02R\x08roleType\x12@\n\x0b\x63reate_time\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x03\xe0\x41\x03R\ncreateTime\x12@\n\x0bupdate_time\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x03\xe0\x41\x03R\nupdateTime\x12&\n\x0c\x63reator_name\x18\x06 \x01(\tB\x03\xe0\x41\x03R\x0b\x63reatorName:X\xea\x41U\n%project.api.audiotool.com/ProjectRole\x12\x1fprojects/{project}/roles/{role}*\x05roles2\x04role*\xe0\x01\n\x0fProjectRoleType\x12!\n\x1dPROJECT_ROLE_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n\x17PROJECT_ROLE_TYPE_OWNER\x10\x01\x12\'\n#PROJECT_ROLE_TYPE_OWNER_UNPUBLISHED\x10\x02\x12\x1c\n\x18PROJECT_ROLE_TYPE_EDITOR\x10\x03\x12(\n$PROJECT_ROLE_TYPE_EDITOR_UNPUBLISHED\x10\x04\x12\x1c\n\x18PROJECT_ROLE_TYPE_VIEWER\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audiotool.project.v1.project_role_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROJECTROLE'].fields_by_name['name']._loaded_options = None
  _globals['_PROJECTROLE'].fields_by_name['name']._serialized_options = b'\340A\010'
  _globals['_PROJECTROLE'].fields_by_name['user_name']._loaded_options = None
  _globals['_PROJECTROLE'].fields_by_name['user_name']._serialized_options = b'\340A\002'
  _globals['_PROJECTROLE'].fields_by_name['role_type']._loaded_options = None
  _globals['_PROJECTROLE'].fields_by_name['role_type']._serialized_options = b'\340A\002'
  _globals['_PROJECTROLE'].fields_by_name['create_time']._loaded_options = None
  _globals['_PROJECTROLE'].fields_by_name['create_time']._serialized_options = b'\340A\003'
  _globals['_PROJECTROLE'].fields_by_name['update_time']._loaded_options = None
  _globals['_PROJECTROLE'].fields_by_name['update_time']._serialized_options = b'\340A\003'
  _globals['_PROJECTROLE'].fields_by_name['creator_name']._loaded_options = None
  _globals['_PROJECTROLE'].fields_by_name['creator_name']._serialized_options = b'\340A\003'
  _globals['_PROJECTROLE']._loaded_options = None
  _globals['_PROJECTROLE']._serialized_options = b'\352AU\n%project.api.audiotool.com/ProjectRole\022\037projects/{project}/roles/{role}*\005roles2\004role'
  _globals['_PROJECTROLETYPE']._serialized_start=569
  _globals['_PROJECTROLETYPE']._serialized_end=793
  _globals['_PROJECTROLE']._serialized_start=159
  _globals['_PROJECTROLE']._serialized_end=566
# @@protoc_insertion_point(module_scope)
