# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audiotool/project/v1/session.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'audiotool/project/v1/session.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from audiotool.project.v1 import project_pb2 as audiotool_dot_project_dot_v1_dot_project__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"audiotool/project/v1/session.proto\x12\x14\x61udiotool.project.v1\x1a\"audiotool/project/v1/project.proto\"\x96\x02\n\x07Session\x12\x37\n\x07project\x18\x01 \x01(\x0b\x32\x1d.audiotool.project.v1.ProjectR\x07project\x12\x30\n\x14\x64ocument_service_url\x18\x02 \x01(\tR\x12\x64ocumentServiceUrl\x12*\n\x11studio_prefix_url\x18\x03 \x01(\tR\x0fstudioPrefixUrl\x12=\n\x1b\x64ocument_service_prefix_url\x18\x04 \x01(\tR\x18\x64ocumentServicePrefixUrl\x12\x35\n\x17\x61udio_engine_prefix_url\x18\x05 \x01(\tR\x14\x61udioEnginePrefixUrlb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audiotool.project.v1.session_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SESSION']._serialized_start=97
  _globals['_SESSION']._serialized_end=375
# @@protoc_insertion_point(module_scope)
