# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audiotool/project/v1/sync_track_info.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'audiotool/project/v1/sync_track_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from audiotool.project.v1 import project_pb2 as audiotool_dot_project_dot_v1_dot_project__pb2
from audiotool.project.v1 import project_service_pb2 as audiotool_dot_project_dot_v1_dot_project__service__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*audiotool/project/v1/sync_track_info.proto\x12\x14\x61udiotool.project.v1\x1a\"audiotool/project/v1/project.proto\x1a*audiotool/project/v1/project_service.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdc\x02\n\rSyncTrackInfo\x12\x37\n\x07project\x18\x01 \x01(\x0b\x32\x1d.audiotool.project.v1.ProjectR\x07project\x12\x37\n\x04mode\x18\x02 \x01(\x0e\x32#.audiotool.project.v1.SyncTrackModeR\x04mode\x12!\n\x0c\x63ommit_index\x18\x03 \x01(\rR\x0b\x63ommitIndex\x12\x1d\n\ntrack_name\x18\x04 \x01(\tR\ttrackName\x12\x1b\n\tuser_name\x18\x05 \x01(\tR\x08userName\x12;\n\x0b\x63reate_time\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\ncreateTime\x12=\n\x06status\x18\x07 \x01(\x0e\x32%.audiotool.project.v1.SyncTrackStatusR\x06status*\x8f\x02\n\x0fSyncTrackStatus\x12!\n\x1dSYNC_TRACK_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n\x19SYNC_TRACK_STATUS_STARTED\x10\x01\x12%\n!SYNC_TRACK_STATUS_AUDIO_RENDERING\x10\x03\x12$\n SYNC_TRACK_STATUS_AUDIO_RENDERED\x10\x04\x12&\n\"SYNC_TRACK_STATUS_AUDIO_CONVERTING\x10\x05\x12%\n!SYNC_TRACK_STATUS_AUDIO_CONVERTED\x10\x06\x12\x1e\n\x1aSYNC_TRACK_STATUS_FINISHED\x10\x07\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audiotool.project.v1.sync_track_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SYNCTRACKSTATUS']._serialized_start=533
  _globals['_SYNCTRACKSTATUS']._serialized_end=804
  _globals['_SYNCTRACKINFO']._serialized_start=182
  _globals['_SYNCTRACKINFO']._serialized_end=530
# @@protoc_insertion_point(module_scope)
