# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audiotool/user/v1/settings.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'audiotool/user/v1/settings.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import resource_pb2 as google_dot_api_dot_resource__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n audiotool/user/v1/settings.proto\x12\x11\x61udiotool.user.v1\x1a\x19google/api/resource.proto\"\xd0\x05\n\x08Settings\x12S\n\x16user_page_comment_mode\x18\x01 \x01(\x0e\x32\x1e.audiotool.user.v1.CommentModeR\x13userPageCommentMode\x12[\n\x1a\x64\x65\x66\x61ult_track_comment_mode\x18\x02 \x01(\x0e\x32\x1e.audiotool.user.v1.CommentModeR\x17\x64\x65\x66\x61ultTrackCommentMode\x12\x61\n\x1d\x64\x65\x66\x61ult_playlist_comment_mode\x18\x03 \x01(\x0e\x32\x1e.audiotool.user.v1.CommentModeR\x1a\x64\x65\x66\x61ultPlaylistCommentMode\x12,\n\x12show_online_status\x18\x04 \x01(\x08R\x10showOnlineStatus\x12(\n\x10show_as_listener\x18\x05 \x01(\x08R\x0eshowAsListener\x12\x33\n\x15newsletter_subscriber\x18\x06 \x01(\x08R\x14newsletterSubscriber\x12G\n!allow_links_on_user_page_comments\x18\x07 \x01(\x08R\x1c\x61llowLinksOnUserPageComments\x12@\n\x1d\x61llow_links_on_track_comments\x18\x08 \x01(\x08R\x19\x61llowLinksOnTrackComments\x12\x46\n allow_links_on_playlist_comments\x18\t \x01(\x08R\x1c\x61llowLinksOnPlaylistComments:O\xea\x41L\n\x1fuser.api.audiotool.com/Settings\x12\x15users/{user}/settings*\x08settings2\x08settings*\x81\x01\n\x0b\x43ommentMode\x12\x1c\n\x18\x43OMMENT_MODE_UNSPECIFIED\x10\x00\x12\x17\n\x13\x43OMMENT_MODE_PUBLIC\x10\x01\x12 \n\x1c\x43OMMENT_MODE_USERS_FOLLOWING\x10\x02\x12\x19\n\x15\x43OMMENT_MODE_DISABLED\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audiotool.user.v1.settings_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETTINGS']._loaded_options = None
  _globals['_SETTINGS']._serialized_options = b'\352AL\n\037user.api.audiotool.com/Settings\022\025users/{user}/settings*\010settings2\010settings'
  _globals['_COMMENTMODE']._serialized_start=806
  _globals['_COMMENTMODE']._serialized_end=935
  _globals['_SETTINGS']._serialized_start=83
  _globals['_SETTINGS']._serialized_end=803
# @@protoc_insertion_point(module_scope)
