# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: audiotool/user/v1/user_service.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import audiotool.user.v1.user_service_pb2 as audiotool_dot_user_dot_v1_dot_user__service__pb2


class UserService(Protocol):
    async def list_users(self, request: audiotool_dot_user_dot_v1_dot_user__service__pb2.ListUsersRequest, ctx: RequestContext) -> audiotool_dot_user_dot_v1_dot_user__service__pb2.ListUsersResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_user(self, request: audiotool_dot_user_dot_v1_dot_user__service__pb2.GetUserRequest, ctx: RequestContext) -> audiotool_dot_user_dot_v1_dot_user__service__pb2.GetUserResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_user(self, request: audiotool_dot_user_dot_v1_dot_user__service__pb2.DeleteUserRequest, ctx: RequestContext) -> audiotool_dot_user_dot_v1_dot_user__service__pb2.DeleteUserResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def update_user(self, request: audiotool_dot_user_dot_v1_dot_user__service__pb2.UpdateUserRequest, ctx: RequestContext) -> audiotool_dot_user_dot_v1_dot_user__service__pb2.UpdateUserResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_settings(self, request: audiotool_dot_user_dot_v1_dot_user__service__pb2.GetSettingsRequest, ctx: RequestContext) -> audiotool_dot_user_dot_v1_dot_user__service__pb2.GetSettingsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def update_settings(self, request: audiotool_dot_user_dot_v1_dot_user__service__pb2.UpdateSettingsRequest, ctx: RequestContext) -> audiotool_dot_user_dot_v1_dot_user__service__pb2.UpdateSettingsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def upload_avatar(self, request: audiotool_dot_user_dot_v1_dot_user__service__pb2.UploadAvatarRequest, ctx: RequestContext) -> audiotool_dot_user_dot_v1_dot_user__service__pb2.UploadAvatarResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class UserServiceASGIApplication(ConnectASGIApplication[UserService]):
    def __init__(self, service: UserService | AsyncGenerator[UserService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/audiotool.user.v1.UserService/ListUsers": Endpoint.unary(
                    method=MethodInfo(
                        name="ListUsers",
                        service_name="audiotool.user.v1.UserService",
                        input=audiotool_dot_user_dot_v1_dot_user__service__pb2.ListUsersRequest,
                        output=audiotool_dot_user_dot_v1_dot_user__service__pb2.ListUsersResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_users,
                ),
                "/audiotool.user.v1.UserService/GetUser": Endpoint.unary(
                    method=MethodInfo(
                        name="GetUser",
                        service_name="audiotool.user.v1.UserService",
                        input=audiotool_dot_user_dot_v1_dot_user__service__pb2.GetUserRequest,
                        output=audiotool_dot_user_dot_v1_dot_user__service__pb2.GetUserResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_user,
                ),
                "/audiotool.user.v1.UserService/DeleteUser": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteUser",
                        service_name="audiotool.user.v1.UserService",
                        input=audiotool_dot_user_dot_v1_dot_user__service__pb2.DeleteUserRequest,
                        output=audiotool_dot_user_dot_v1_dot_user__service__pb2.DeleteUserResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_user,
                ),
                "/audiotool.user.v1.UserService/UpdateUser": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateUser",
                        service_name="audiotool.user.v1.UserService",
                        input=audiotool_dot_user_dot_v1_dot_user__service__pb2.UpdateUserRequest,
                        output=audiotool_dot_user_dot_v1_dot_user__service__pb2.UpdateUserResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.update_user,
                ),
                "/audiotool.user.v1.UserService/GetSettings": Endpoint.unary(
                    method=MethodInfo(
                        name="GetSettings",
                        service_name="audiotool.user.v1.UserService",
                        input=audiotool_dot_user_dot_v1_dot_user__service__pb2.GetSettingsRequest,
                        output=audiotool_dot_user_dot_v1_dot_user__service__pb2.GetSettingsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_settings,
                ),
                "/audiotool.user.v1.UserService/UpdateSettings": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateSettings",
                        service_name="audiotool.user.v1.UserService",
                        input=audiotool_dot_user_dot_v1_dot_user__service__pb2.UpdateSettingsRequest,
                        output=audiotool_dot_user_dot_v1_dot_user__service__pb2.UpdateSettingsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.update_settings,
                ),
                "/audiotool.user.v1.UserService/UploadAvatar": Endpoint.unary(
                    method=MethodInfo(
                        name="UploadAvatar",
                        service_name="audiotool.user.v1.UserService",
                        input=audiotool_dot_user_dot_v1_dot_user__service__pb2.UploadAvatarRequest,
                        output=audiotool_dot_user_dot_v1_dot_user__service__pb2.UploadAvatarResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.upload_avatar,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/audiotool.user.v1.UserService"


class UserServiceClient(ConnectClient):
    async def list_users(
        self,
        request: audiotool_dot_user_dot_v1_dot_user__service__pb2.ListUsersRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_user_dot_v1_dot_user__service__pb2.ListUsersResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListUsers",
                service_name="audiotool.user.v1.UserService",
                input=audiotool_dot_user_dot_v1_dot_user__service__pb2.ListUsersRequest,
                output=audiotool_dot_user_dot_v1_dot_user__service__pb2.ListUsersResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_user(
        self,
        request: audiotool_dot_user_dot_v1_dot_user__service__pb2.GetUserRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_user_dot_v1_dot_user__service__pb2.GetUserResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetUser",
                service_name="audiotool.user.v1.UserService",
                input=audiotool_dot_user_dot_v1_dot_user__service__pb2.GetUserRequest,
                output=audiotool_dot_user_dot_v1_dot_user__service__pb2.GetUserResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_user(
        self,
        request: audiotool_dot_user_dot_v1_dot_user__service__pb2.DeleteUserRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_user_dot_v1_dot_user__service__pb2.DeleteUserResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteUser",
                service_name="audiotool.user.v1.UserService",
                input=audiotool_dot_user_dot_v1_dot_user__service__pb2.DeleteUserRequest,
                output=audiotool_dot_user_dot_v1_dot_user__service__pb2.DeleteUserResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_user(
        self,
        request: audiotool_dot_user_dot_v1_dot_user__service__pb2.UpdateUserRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_user_dot_v1_dot_user__service__pb2.UpdateUserResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateUser",
                service_name="audiotool.user.v1.UserService",
                input=audiotool_dot_user_dot_v1_dot_user__service__pb2.UpdateUserRequest,
                output=audiotool_dot_user_dot_v1_dot_user__service__pb2.UpdateUserResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_settings(
        self,
        request: audiotool_dot_user_dot_v1_dot_user__service__pb2.GetSettingsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_user_dot_v1_dot_user__service__pb2.GetSettingsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetSettings",
                service_name="audiotool.user.v1.UserService",
                input=audiotool_dot_user_dot_v1_dot_user__service__pb2.GetSettingsRequest,
                output=audiotool_dot_user_dot_v1_dot_user__service__pb2.GetSettingsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_settings(
        self,
        request: audiotool_dot_user_dot_v1_dot_user__service__pb2.UpdateSettingsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_user_dot_v1_dot_user__service__pb2.UpdateSettingsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateSettings",
                service_name="audiotool.user.v1.UserService",
                input=audiotool_dot_user_dot_v1_dot_user__service__pb2.UpdateSettingsRequest,
                output=audiotool_dot_user_dot_v1_dot_user__service__pb2.UpdateSettingsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def upload_avatar(
        self,
        request: audiotool_dot_user_dot_v1_dot_user__service__pb2.UploadAvatarRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_user_dot_v1_dot_user__service__pb2.UploadAvatarResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UploadAvatar",
                service_name="audiotool.user.v1.UserService",
                input=audiotool_dot_user_dot_v1_dot_user__service__pb2.UploadAvatarRequest,
                output=audiotool_dot_user_dot_v1_dot_user__service__pb2.UploadAvatarResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class UserServiceSync(Protocol):
    def list_users(self, request: audiotool_dot_user_dot_v1_dot_user__service__pb2.ListUsersRequest, ctx: RequestContext) -> audiotool_dot_user_dot_v1_dot_user__service__pb2.ListUsersResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_user(self, request: audiotool_dot_user_dot_v1_dot_user__service__pb2.GetUserRequest, ctx: RequestContext) -> audiotool_dot_user_dot_v1_dot_user__service__pb2.GetUserResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_user(self, request: audiotool_dot_user_dot_v1_dot_user__service__pb2.DeleteUserRequest, ctx: RequestContext) -> audiotool_dot_user_dot_v1_dot_user__service__pb2.DeleteUserResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def update_user(self, request: audiotool_dot_user_dot_v1_dot_user__service__pb2.UpdateUserRequest, ctx: RequestContext) -> audiotool_dot_user_dot_v1_dot_user__service__pb2.UpdateUserResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_settings(self, request: audiotool_dot_user_dot_v1_dot_user__service__pb2.GetSettingsRequest, ctx: RequestContext) -> audiotool_dot_user_dot_v1_dot_user__service__pb2.GetSettingsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def update_settings(self, request: audiotool_dot_user_dot_v1_dot_user__service__pb2.UpdateSettingsRequest, ctx: RequestContext) -> audiotool_dot_user_dot_v1_dot_user__service__pb2.UpdateSettingsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def upload_avatar(self, request: audiotool_dot_user_dot_v1_dot_user__service__pb2.UploadAvatarRequest, ctx: RequestContext) -> audiotool_dot_user_dot_v1_dot_user__service__pb2.UploadAvatarResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class UserServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: UserServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/audiotool.user.v1.UserService/ListUsers": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListUsers",
                        service_name="audiotool.user.v1.UserService",
                        input=audiotool_dot_user_dot_v1_dot_user__service__pb2.ListUsersRequest,
                        output=audiotool_dot_user_dot_v1_dot_user__service__pb2.ListUsersResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_users,
                ),
                "/audiotool.user.v1.UserService/GetUser": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetUser",
                        service_name="audiotool.user.v1.UserService",
                        input=audiotool_dot_user_dot_v1_dot_user__service__pb2.GetUserRequest,
                        output=audiotool_dot_user_dot_v1_dot_user__service__pb2.GetUserResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_user,
                ),
                "/audiotool.user.v1.UserService/DeleteUser": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteUser",
                        service_name="audiotool.user.v1.UserService",
                        input=audiotool_dot_user_dot_v1_dot_user__service__pb2.DeleteUserRequest,
                        output=audiotool_dot_user_dot_v1_dot_user__service__pb2.DeleteUserResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_user,
                ),
                "/audiotool.user.v1.UserService/UpdateUser": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateUser",
                        service_name="audiotool.user.v1.UserService",
                        input=audiotool_dot_user_dot_v1_dot_user__service__pb2.UpdateUserRequest,
                        output=audiotool_dot_user_dot_v1_dot_user__service__pb2.UpdateUserResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_user,
                ),
                "/audiotool.user.v1.UserService/GetSettings": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetSettings",
                        service_name="audiotool.user.v1.UserService",
                        input=audiotool_dot_user_dot_v1_dot_user__service__pb2.GetSettingsRequest,
                        output=audiotool_dot_user_dot_v1_dot_user__service__pb2.GetSettingsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_settings,
                ),
                "/audiotool.user.v1.UserService/UpdateSettings": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateSettings",
                        service_name="audiotool.user.v1.UserService",
                        input=audiotool_dot_user_dot_v1_dot_user__service__pb2.UpdateSettingsRequest,
                        output=audiotool_dot_user_dot_v1_dot_user__service__pb2.UpdateSettingsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_settings,
                ),
                "/audiotool.user.v1.UserService/UploadAvatar": EndpointSync.unary(
                    method=MethodInfo(
                        name="UploadAvatar",
                        service_name="audiotool.user.v1.UserService",
                        input=audiotool_dot_user_dot_v1_dot_user__service__pb2.UploadAvatarRequest,
                        output=audiotool_dot_user_dot_v1_dot_user__service__pb2.UploadAvatarResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.upload_avatar,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/audiotool.user.v1.UserService"


class UserServiceClientSync(ConnectClientSync):
    def list_users(
        self,
        request: audiotool_dot_user_dot_v1_dot_user__service__pb2.ListUsersRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_user_dot_v1_dot_user__service__pb2.ListUsersResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListUsers",
                service_name="audiotool.user.v1.UserService",
                input=audiotool_dot_user_dot_v1_dot_user__service__pb2.ListUsersRequest,
                output=audiotool_dot_user_dot_v1_dot_user__service__pb2.ListUsersResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_user(
        self,
        request: audiotool_dot_user_dot_v1_dot_user__service__pb2.GetUserRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_user_dot_v1_dot_user__service__pb2.GetUserResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetUser",
                service_name="audiotool.user.v1.UserService",
                input=audiotool_dot_user_dot_v1_dot_user__service__pb2.GetUserRequest,
                output=audiotool_dot_user_dot_v1_dot_user__service__pb2.GetUserResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_user(
        self,
        request: audiotool_dot_user_dot_v1_dot_user__service__pb2.DeleteUserRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_user_dot_v1_dot_user__service__pb2.DeleteUserResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteUser",
                service_name="audiotool.user.v1.UserService",
                input=audiotool_dot_user_dot_v1_dot_user__service__pb2.DeleteUserRequest,
                output=audiotool_dot_user_dot_v1_dot_user__service__pb2.DeleteUserResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def update_user(
        self,
        request: audiotool_dot_user_dot_v1_dot_user__service__pb2.UpdateUserRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_user_dot_v1_dot_user__service__pb2.UpdateUserResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateUser",
                service_name="audiotool.user.v1.UserService",
                input=audiotool_dot_user_dot_v1_dot_user__service__pb2.UpdateUserRequest,
                output=audiotool_dot_user_dot_v1_dot_user__service__pb2.UpdateUserResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_settings(
        self,
        request: audiotool_dot_user_dot_v1_dot_user__service__pb2.GetSettingsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_user_dot_v1_dot_user__service__pb2.GetSettingsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetSettings",
                service_name="audiotool.user.v1.UserService",
                input=audiotool_dot_user_dot_v1_dot_user__service__pb2.GetSettingsRequest,
                output=audiotool_dot_user_dot_v1_dot_user__service__pb2.GetSettingsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def update_settings(
        self,
        request: audiotool_dot_user_dot_v1_dot_user__service__pb2.UpdateSettingsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_user_dot_v1_dot_user__service__pb2.UpdateSettingsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateSettings",
                service_name="audiotool.user.v1.UserService",
                input=audiotool_dot_user_dot_v1_dot_user__service__pb2.UpdateSettingsRequest,
                output=audiotool_dot_user_dot_v1_dot_user__service__pb2.UpdateSettingsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def upload_avatar(
        self,
        request: audiotool_dot_user_dot_v1_dot_user__service__pb2.UploadAvatarRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_user_dot_v1_dot_user__service__pb2.UploadAvatarResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UploadAvatar",
                service_name="audiotool.user.v1.UserService",
                input=audiotool_dot_user_dot_v1_dot_user__service__pb2.UploadAvatarRequest,
                output=audiotool_dot_user_dot_v1_dot_user__service__pb2.UploadAvatarResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
