# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audiotool/user/v1/user.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'audiotool/user/v1/user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x61udiotool/user/v1/user.proto\x12\x11\x61udiotool.user.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe1\x03\n\x04User\x12\x17\n\x04name\x18\x01 \x01(\tB\x03\xe0\x41\x05R\x04name\x12&\n\x0c\x64isplay_name\x18\x02 \x01(\tB\x03\xe0\x41\x02R\x0b\x64isplayName\x12@\n\x0b\x63reate_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x03\xe0\x41\x03R\ncreateTime\x12%\n\x0b\x64\x65scription\x18\x04 \x01(\tB\x03\xe0\x41\x01R\x0b\x64\x65scription\x12\"\n\nnum_tracks\x18\x05 \x01(\x05\x42\x03\xe0\x41\x03R\tnumTracks\x12\"\n\nnum_albums\x18\x06 \x01(\x05\x42\x03\xe0\x41\x03R\tnumAlbums\x12(\n\rnum_followers\x18\x07 \x01(\x05\x42\x03\xe0\x41\x03R\x0cnumFollowers\x12(\n\rnum_following\x18\x08 \x01(\x05\x42\x03\xe0\x41\x03R\x0cnumFollowing\x12\x17\n\x04tags\x18\t \x03(\tB\x03\xe0\x41\x01R\x04tags\x12\"\n\navatar_url\x18\n \x01(\tB\x03\xe0\x41\x01R\tavatarUrl\x12\x19\n\x05links\x18\x0b \x03(\tB\x03\xe0\x41\x01R\x05links:;\xea\x41\x38\n\x1buser.api.audiotool.com/User\x12\x0cusers/{user}*\x05users2\x04userb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audiotool.user.v1.user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER'].fields_by_name['name']._loaded_options = None
  _globals['_USER'].fields_by_name['name']._serialized_options = b'\340A\005'
  _globals['_USER'].fields_by_name['display_name']._loaded_options = None
  _globals['_USER'].fields_by_name['display_name']._serialized_options = b'\340A\002'
  _globals['_USER'].fields_by_name['create_time']._loaded_options = None
  _globals['_USER'].fields_by_name['create_time']._serialized_options = b'\340A\003'
  _globals['_USER'].fields_by_name['description']._loaded_options = None
  _globals['_USER'].fields_by_name['description']._serialized_options = b'\340A\001'
  _globals['_USER'].fields_by_name['num_tracks']._loaded_options = None
  _globals['_USER'].fields_by_name['num_tracks']._serialized_options = b'\340A\003'
  _globals['_USER'].fields_by_name['num_albums']._loaded_options = None
  _globals['_USER'].fields_by_name['num_albums']._serialized_options = b'\340A\003'
  _globals['_USER'].fields_by_name['num_followers']._loaded_options = None
  _globals['_USER'].fields_by_name['num_followers']._serialized_options = b'\340A\003'
  _globals['_USER'].fields_by_name['num_following']._loaded_options = None
  _globals['_USER'].fields_by_name['num_following']._serialized_options = b'\340A\003'
  _globals['_USER'].fields_by_name['tags']._loaded_options = None
  _globals['_USER'].fields_by_name['tags']._serialized_options = b'\340A\001'
  _globals['_USER'].fields_by_name['avatar_url']._loaded_options = None
  _globals['_USER'].fields_by_name['avatar_url']._serialized_options = b'\340A\001'
  _globals['_USER'].fields_by_name['links']._loaded_options = None
  _globals['_USER'].fields_by_name['links']._serialized_options = b'\340A\001'
  _globals['_USER']._loaded_options = None
  _globals['_USER']._serialized_options = b'\352A8\n\033user.api.audiotool.com/User\022\014users/{user}*\005users2\004user'
  _globals['_USER']._serialized_start=145
  _globals['_USER']._serialized_end=626
# @@protoc_insertion_point(module_scope)
