# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: audiotool/project/v1/project_role_service.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import audiotool.project.v1.project_role_service_pb2 as audiotool_dot_project_dot_v1_dot_project__role__service__pb2


class ProjectRoleService(Protocol):
    async def list_project_roles(self, request: audiotool_dot_project_dot_v1_dot_project__role__service__pb2.ListProjectRolesRequest, ctx: RequestContext) -> audiotool_dot_project_dot_v1_dot_project__role__service__pb2.ListProjectRolesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def create_project_role(self, request: audiotool_dot_project_dot_v1_dot_project__role__service__pb2.CreateProjectRoleRequest, ctx: RequestContext) -> audiotool_dot_project_dot_v1_dot_project__role__service__pb2.CreateProjectRoleResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_project_role(self, request: audiotool_dot_project_dot_v1_dot_project__role__service__pb2.DeleteProjectRoleRequest, ctx: RequestContext) -> audiotool_dot_project_dot_v1_dot_project__role__service__pb2.DeleteProjectRoleResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def update_project_role(self, request: audiotool_dot_project_dot_v1_dot_project__role__service__pb2.UpdateProjectRoleRequest, ctx: RequestContext) -> audiotool_dot_project_dot_v1_dot_project__role__service__pb2.UpdateProjectRoleResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class ProjectRoleServiceASGIApplication(ConnectASGIApplication[ProjectRoleService]):
    def __init__(self, service: ProjectRoleService | AsyncGenerator[ProjectRoleService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/audiotool.project.v1.ProjectRoleService/ListProjectRoles": Endpoint.unary(
                    method=MethodInfo(
                        name="ListProjectRoles",
                        service_name="audiotool.project.v1.ProjectRoleService",
                        input=audiotool_dot_project_dot_v1_dot_project__role__service__pb2.ListProjectRolesRequest,
                        output=audiotool_dot_project_dot_v1_dot_project__role__service__pb2.ListProjectRolesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_project_roles,
                ),
                "/audiotool.project.v1.ProjectRoleService/CreateProjectRole": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateProjectRole",
                        service_name="audiotool.project.v1.ProjectRoleService",
                        input=audiotool_dot_project_dot_v1_dot_project__role__service__pb2.CreateProjectRoleRequest,
                        output=audiotool_dot_project_dot_v1_dot_project__role__service__pb2.CreateProjectRoleResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_project_role,
                ),
                "/audiotool.project.v1.ProjectRoleService/DeleteProjectRole": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteProjectRole",
                        service_name="audiotool.project.v1.ProjectRoleService",
                        input=audiotool_dot_project_dot_v1_dot_project__role__service__pb2.DeleteProjectRoleRequest,
                        output=audiotool_dot_project_dot_v1_dot_project__role__service__pb2.DeleteProjectRoleResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_project_role,
                ),
                "/audiotool.project.v1.ProjectRoleService/UpdateProjectRole": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateProjectRole",
                        service_name="audiotool.project.v1.ProjectRoleService",
                        input=audiotool_dot_project_dot_v1_dot_project__role__service__pb2.UpdateProjectRoleRequest,
                        output=audiotool_dot_project_dot_v1_dot_project__role__service__pb2.UpdateProjectRoleResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.update_project_role,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/audiotool.project.v1.ProjectRoleService"


class ProjectRoleServiceClient(ConnectClient):
    async def list_project_roles(
        self,
        request: audiotool_dot_project_dot_v1_dot_project__role__service__pb2.ListProjectRolesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_project_dot_v1_dot_project__role__service__pb2.ListProjectRolesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListProjectRoles",
                service_name="audiotool.project.v1.ProjectRoleService",
                input=audiotool_dot_project_dot_v1_dot_project__role__service__pb2.ListProjectRolesRequest,
                output=audiotool_dot_project_dot_v1_dot_project__role__service__pb2.ListProjectRolesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def create_project_role(
        self,
        request: audiotool_dot_project_dot_v1_dot_project__role__service__pb2.CreateProjectRoleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_project_dot_v1_dot_project__role__service__pb2.CreateProjectRoleResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateProjectRole",
                service_name="audiotool.project.v1.ProjectRoleService",
                input=audiotool_dot_project_dot_v1_dot_project__role__service__pb2.CreateProjectRoleRequest,
                output=audiotool_dot_project_dot_v1_dot_project__role__service__pb2.CreateProjectRoleResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_project_role(
        self,
        request: audiotool_dot_project_dot_v1_dot_project__role__service__pb2.DeleteProjectRoleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_project_dot_v1_dot_project__role__service__pb2.DeleteProjectRoleResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteProjectRole",
                service_name="audiotool.project.v1.ProjectRoleService",
                input=audiotool_dot_project_dot_v1_dot_project__role__service__pb2.DeleteProjectRoleRequest,
                output=audiotool_dot_project_dot_v1_dot_project__role__service__pb2.DeleteProjectRoleResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_project_role(
        self,
        request: audiotool_dot_project_dot_v1_dot_project__role__service__pb2.UpdateProjectRoleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_project_dot_v1_dot_project__role__service__pb2.UpdateProjectRoleResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateProjectRole",
                service_name="audiotool.project.v1.ProjectRoleService",
                input=audiotool_dot_project_dot_v1_dot_project__role__service__pb2.UpdateProjectRoleRequest,
                output=audiotool_dot_project_dot_v1_dot_project__role__service__pb2.UpdateProjectRoleResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class ProjectRoleServiceSync(Protocol):
    def list_project_roles(self, request: audiotool_dot_project_dot_v1_dot_project__role__service__pb2.ListProjectRolesRequest, ctx: RequestContext) -> audiotool_dot_project_dot_v1_dot_project__role__service__pb2.ListProjectRolesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def create_project_role(self, request: audiotool_dot_project_dot_v1_dot_project__role__service__pb2.CreateProjectRoleRequest, ctx: RequestContext) -> audiotool_dot_project_dot_v1_dot_project__role__service__pb2.CreateProjectRoleResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_project_role(self, request: audiotool_dot_project_dot_v1_dot_project__role__service__pb2.DeleteProjectRoleRequest, ctx: RequestContext) -> audiotool_dot_project_dot_v1_dot_project__role__service__pb2.DeleteProjectRoleResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def update_project_role(self, request: audiotool_dot_project_dot_v1_dot_project__role__service__pb2.UpdateProjectRoleRequest, ctx: RequestContext) -> audiotool_dot_project_dot_v1_dot_project__role__service__pb2.UpdateProjectRoleResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class ProjectRoleServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: ProjectRoleServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/audiotool.project.v1.ProjectRoleService/ListProjectRoles": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListProjectRoles",
                        service_name="audiotool.project.v1.ProjectRoleService",
                        input=audiotool_dot_project_dot_v1_dot_project__role__service__pb2.ListProjectRolesRequest,
                        output=audiotool_dot_project_dot_v1_dot_project__role__service__pb2.ListProjectRolesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_project_roles,
                ),
                "/audiotool.project.v1.ProjectRoleService/CreateProjectRole": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateProjectRole",
                        service_name="audiotool.project.v1.ProjectRoleService",
                        input=audiotool_dot_project_dot_v1_dot_project__role__service__pb2.CreateProjectRoleRequest,
                        output=audiotool_dot_project_dot_v1_dot_project__role__service__pb2.CreateProjectRoleResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_project_role,
                ),
                "/audiotool.project.v1.ProjectRoleService/DeleteProjectRole": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteProjectRole",
                        service_name="audiotool.project.v1.ProjectRoleService",
                        input=audiotool_dot_project_dot_v1_dot_project__role__service__pb2.DeleteProjectRoleRequest,
                        output=audiotool_dot_project_dot_v1_dot_project__role__service__pb2.DeleteProjectRoleResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_project_role,
                ),
                "/audiotool.project.v1.ProjectRoleService/UpdateProjectRole": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateProjectRole",
                        service_name="audiotool.project.v1.ProjectRoleService",
                        input=audiotool_dot_project_dot_v1_dot_project__role__service__pb2.UpdateProjectRoleRequest,
                        output=audiotool_dot_project_dot_v1_dot_project__role__service__pb2.UpdateProjectRoleResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_project_role,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/audiotool.project.v1.ProjectRoleService"


class ProjectRoleServiceClientSync(ConnectClientSync):
    def list_project_roles(
        self,
        request: audiotool_dot_project_dot_v1_dot_project__role__service__pb2.ListProjectRolesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_project_dot_v1_dot_project__role__service__pb2.ListProjectRolesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListProjectRoles",
                service_name="audiotool.project.v1.ProjectRoleService",
                input=audiotool_dot_project_dot_v1_dot_project__role__service__pb2.ListProjectRolesRequest,
                output=audiotool_dot_project_dot_v1_dot_project__role__service__pb2.ListProjectRolesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def create_project_role(
        self,
        request: audiotool_dot_project_dot_v1_dot_project__role__service__pb2.CreateProjectRoleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_project_dot_v1_dot_project__role__service__pb2.CreateProjectRoleResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateProjectRole",
                service_name="audiotool.project.v1.ProjectRoleService",
                input=audiotool_dot_project_dot_v1_dot_project__role__service__pb2.CreateProjectRoleRequest,
                output=audiotool_dot_project_dot_v1_dot_project__role__service__pb2.CreateProjectRoleResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_project_role(
        self,
        request: audiotool_dot_project_dot_v1_dot_project__role__service__pb2.DeleteProjectRoleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_project_dot_v1_dot_project__role__service__pb2.DeleteProjectRoleResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteProjectRole",
                service_name="audiotool.project.v1.ProjectRoleService",
                input=audiotool_dot_project_dot_v1_dot_project__role__service__pb2.DeleteProjectRoleRequest,
                output=audiotool_dot_project_dot_v1_dot_project__role__service__pb2.DeleteProjectRoleResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def update_project_role(
        self,
        request: audiotool_dot_project_dot_v1_dot_project__role__service__pb2.UpdateProjectRoleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_project_dot_v1_dot_project__role__service__pb2.UpdateProjectRoleResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateProjectRole",
                service_name="audiotool.project.v1.ProjectRoleService",
                input=audiotool_dot_project_dot_v1_dot_project__role__service__pb2.UpdateProjectRoleRequest,
                output=audiotool_dot_project_dot_v1_dot_project__role__service__pb2.UpdateProjectRoleResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
