# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: audiotool/event/v1/event_service.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import audiotool.event.v1.event_service_pb2 as audiotool_dot_event_dot_v1_dot_event__service__pb2


class EventService(Protocol):
    def listen(self, request: audiotool_dot_event_dot_v1_dot_event__service__pb2.ListenRequest, ctx: RequestContext) -> AsyncIterator[audiotool_dot_event_dot_v1_dot_event__service__pb2.ListenResponse]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class EventServiceASGIApplication(ConnectASGIApplication[EventService]):
    def __init__(self, service: EventService | AsyncGenerator[EventService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/audiotool.event.v1.EventService/Listen": Endpoint.server_stream(
                    method=MethodInfo(
                        name="Listen",
                        service_name="audiotool.event.v1.EventService",
                        input=audiotool_dot_event_dot_v1_dot_event__service__pb2.ListenRequest,
                        output=audiotool_dot_event_dot_v1_dot_event__service__pb2.ListenResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.listen,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/audiotool.event.v1.EventService"


class EventServiceClient(ConnectClient):
    def listen(
        self,
        request: audiotool_dot_event_dot_v1_dot_event__service__pb2.ListenRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> AsyncIterator[audiotool_dot_event_dot_v1_dot_event__service__pb2.ListenResponse]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="Listen",
                service_name="audiotool.event.v1.EventService",
                input=audiotool_dot_event_dot_v1_dot_event__service__pb2.ListenRequest,
                output=audiotool_dot_event_dot_v1_dot_event__service__pb2.ListenResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class EventServiceSync(Protocol):
    def listen(self, request: audiotool_dot_event_dot_v1_dot_event__service__pb2.ListenRequest, ctx: RequestContext) -> Iterator[audiotool_dot_event_dot_v1_dot_event__service__pb2.ListenResponse]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class EventServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: EventServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/audiotool.event.v1.EventService/Listen": EndpointSync.server_stream(
                    method=MethodInfo(
                        name="Listen",
                        service_name="audiotool.event.v1.EventService",
                        input=audiotool_dot_event_dot_v1_dot_event__service__pb2.ListenRequest,
                        output=audiotool_dot_event_dot_v1_dot_event__service__pb2.ListenResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.listen,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/audiotool.event.v1.EventService"


class EventServiceClientSync(ConnectClientSync):
    def listen(
        self,
        request: audiotool_dot_event_dot_v1_dot_event__service__pb2.ListenRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> Iterator[audiotool_dot_event_dot_v1_dot_event__service__pb2.ListenResponse]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="Listen",
                service_name="audiotool.event.v1.EventService",
                input=audiotool_dot_event_dot_v1_dot_event__service__pb2.ListenRequest,
                output=audiotool_dot_event_dot_v1_dot_event__service__pb2.ListenResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
