# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audiotool/event/v1/event_service.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'audiotool/event/v1/event_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from audiotool.event.v1 import event_pb2 as audiotool_dot_event_dot_v1_dot_event__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&audiotool/event/v1/event_service.proto\x12\x12\x61udiotool.event.v1\x1a\x1e\x61udiotool/event/v1/event.proto\"\x0f\n\rListenRequest\"A\n\x0eListenResponse\x12/\n\x05\x65vent\x18\x01 \x01(\x0b\x32\x19.audiotool.event.v1.EventR\x05\x65vent2a\n\x0c\x45ventService\x12Q\n\x06Listen\x12!.audiotool.event.v1.ListenRequest\x1a\".audiotool.event.v1.ListenResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audiotool.event.v1.event_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTENREQUEST']._serialized_start=94
  _globals['_LISTENREQUEST']._serialized_end=109
  _globals['_LISTENRESPONSE']._serialized_start=111
  _globals['_LISTENRESPONSE']._serialized_end=176
  _globals['_EVENTSERVICE']._serialized_start=178
  _globals['_EVENTSERVICE']._serialized_end=275
# @@protoc_insertion_point(module_scope)
