# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: audiotool/favorite/v1/favorite_service.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import audiotool.favorite.v1.favorite_service_pb2 as audiotool_dot_favorite_dot_v1_dot_favorite__service__pb2


class FavoriteService(Protocol):
    async def create_favorite(self, request: audiotool_dot_favorite_dot_v1_dot_favorite__service__pb2.CreateFavoriteRequest, ctx: RequestContext) -> audiotool_dot_favorite_dot_v1_dot_favorite__service__pb2.CreateFavoriteResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_favorite(self, request: audiotool_dot_favorite_dot_v1_dot_favorite__service__pb2.DeleteFavoriteRequest, ctx: RequestContext) -> audiotool_dot_favorite_dot_v1_dot_favorite__service__pb2.DeleteFavoriteResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class FavoriteServiceASGIApplication(ConnectASGIApplication[FavoriteService]):
    def __init__(self, service: FavoriteService | AsyncGenerator[FavoriteService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/audiotool.favorite.v1.FavoriteService/CreateFavorite": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateFavorite",
                        service_name="audiotool.favorite.v1.FavoriteService",
                        input=audiotool_dot_favorite_dot_v1_dot_favorite__service__pb2.CreateFavoriteRequest,
                        output=audiotool_dot_favorite_dot_v1_dot_favorite__service__pb2.CreateFavoriteResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_favorite,
                ),
                "/audiotool.favorite.v1.FavoriteService/DeleteFavorite": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteFavorite",
                        service_name="audiotool.favorite.v1.FavoriteService",
                        input=audiotool_dot_favorite_dot_v1_dot_favorite__service__pb2.DeleteFavoriteRequest,
                        output=audiotool_dot_favorite_dot_v1_dot_favorite__service__pb2.DeleteFavoriteResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_favorite,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/audiotool.favorite.v1.FavoriteService"


class FavoriteServiceClient(ConnectClient):
    async def create_favorite(
        self,
        request: audiotool_dot_favorite_dot_v1_dot_favorite__service__pb2.CreateFavoriteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_favorite_dot_v1_dot_favorite__service__pb2.CreateFavoriteResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateFavorite",
                service_name="audiotool.favorite.v1.FavoriteService",
                input=audiotool_dot_favorite_dot_v1_dot_favorite__service__pb2.CreateFavoriteRequest,
                output=audiotool_dot_favorite_dot_v1_dot_favorite__service__pb2.CreateFavoriteResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_favorite(
        self,
        request: audiotool_dot_favorite_dot_v1_dot_favorite__service__pb2.DeleteFavoriteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_favorite_dot_v1_dot_favorite__service__pb2.DeleteFavoriteResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteFavorite",
                service_name="audiotool.favorite.v1.FavoriteService",
                input=audiotool_dot_favorite_dot_v1_dot_favorite__service__pb2.DeleteFavoriteRequest,
                output=audiotool_dot_favorite_dot_v1_dot_favorite__service__pb2.DeleteFavoriteResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class FavoriteServiceSync(Protocol):
    def create_favorite(self, request: audiotool_dot_favorite_dot_v1_dot_favorite__service__pb2.CreateFavoriteRequest, ctx: RequestContext) -> audiotool_dot_favorite_dot_v1_dot_favorite__service__pb2.CreateFavoriteResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_favorite(self, request: audiotool_dot_favorite_dot_v1_dot_favorite__service__pb2.DeleteFavoriteRequest, ctx: RequestContext) -> audiotool_dot_favorite_dot_v1_dot_favorite__service__pb2.DeleteFavoriteResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class FavoriteServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: FavoriteServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/audiotool.favorite.v1.FavoriteService/CreateFavorite": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateFavorite",
                        service_name="audiotool.favorite.v1.FavoriteService",
                        input=audiotool_dot_favorite_dot_v1_dot_favorite__service__pb2.CreateFavoriteRequest,
                        output=audiotool_dot_favorite_dot_v1_dot_favorite__service__pb2.CreateFavoriteResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_favorite,
                ),
                "/audiotool.favorite.v1.FavoriteService/DeleteFavorite": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteFavorite",
                        service_name="audiotool.favorite.v1.FavoriteService",
                        input=audiotool_dot_favorite_dot_v1_dot_favorite__service__pb2.DeleteFavoriteRequest,
                        output=audiotool_dot_favorite_dot_v1_dot_favorite__service__pb2.DeleteFavoriteResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_favorite,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/audiotool.favorite.v1.FavoriteService"


class FavoriteServiceClientSync(ConnectClientSync):
    def create_favorite(
        self,
        request: audiotool_dot_favorite_dot_v1_dot_favorite__service__pb2.CreateFavoriteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_favorite_dot_v1_dot_favorite__service__pb2.CreateFavoriteResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateFavorite",
                service_name="audiotool.favorite.v1.FavoriteService",
                input=audiotool_dot_favorite_dot_v1_dot_favorite__service__pb2.CreateFavoriteRequest,
                output=audiotool_dot_favorite_dot_v1_dot_favorite__service__pb2.CreateFavoriteResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_favorite(
        self,
        request: audiotool_dot_favorite_dot_v1_dot_favorite__service__pb2.DeleteFavoriteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> audiotool_dot_favorite_dot_v1_dot_favorite__service__pb2.DeleteFavoriteResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteFavorite",
                service_name="audiotool.favorite.v1.FavoriteService",
                input=audiotool_dot_favorite_dot_v1_dot_favorite__service__pb2.DeleteFavoriteRequest,
                output=audiotool_dot_favorite_dot_v1_dot_favorite__service__pb2.DeleteFavoriteResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
