# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audiotool/favorite/v1/favorite_service.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'audiotool/favorite/v1/favorite_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from google.api import resource_pb2 as google_dot_api_dot_resource__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,audiotool/favorite/v1/favorite_service.proto\x12\x15\x61udiotool.favorite.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\"\x9d\x02\n\x15\x43reateFavoriteRequest\x12\x43\n\x06parent\x18\x01 \x01(\tB+\xe0\x41\x02\xfa\x41%\x12#favorite.api.audiotool.com/FavoriteR\x06parent\x12 \n\tuser_name\x18\x02 \x01(\tB\x03\xe0\x41\x01R\x08userName:\x9c\x01\xea\x41\x98\x01\n#favorite.api.audiotool.com/Favorite\x12\x0etracks/{track}\x12\x10samples/{sample}\x12\x10presets/{preset}\x12\x14playlists/{playlist}\x12\x12\x63ontests/{contest}\x12\x13users/{target_user}\"\x18\n\x16\x43reateFavoriteResponse\"X\n\x15\x44\x65leteFavoriteRequest\x12?\n\x04name\x18\x01 \x01(\tB+\xe0\x41\x02\xfa\x41%\n#favorite.api.audiotool.com/FavoriteR\x04name\"\x18\n\x16\x44\x65leteFavoriteResponse2\xf3\x01\n\x0f\x46\x61voriteService\x12o\n\x0e\x43reateFavorite\x12,.audiotool.favorite.v1.CreateFavoriteRequest\x1a-.audiotool.favorite.v1.CreateFavoriteResponse\"\x00\x12o\n\x0e\x44\x65leteFavorite\x12,.audiotool.favorite.v1.DeleteFavoriteRequest\x1a-.audiotool.favorite.v1.DeleteFavoriteResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audiotool.favorite.v1.favorite_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEFAVORITEREQUEST'].fields_by_name['parent']._loaded_options = None
  _globals['_CREATEFAVORITEREQUEST'].fields_by_name['parent']._serialized_options = b'\340A\002\372A%\022#favorite.api.audiotool.com/Favorite'
  _globals['_CREATEFAVORITEREQUEST'].fields_by_name['user_name']._loaded_options = None
  _globals['_CREATEFAVORITEREQUEST'].fields_by_name['user_name']._serialized_options = b'\340A\001'
  _globals['_CREATEFAVORITEREQUEST']._loaded_options = None
  _globals['_CREATEFAVORITEREQUEST']._serialized_options = b'\352A\230\001\n#favorite.api.audiotool.com/Favorite\022\016tracks/{track}\022\020samples/{sample}\022\020presets/{preset}\022\024playlists/{playlist}\022\022contests/{contest}\022\023users/{target_user}'
  _globals['_DELETEFAVORITEREQUEST'].fields_by_name['name']._loaded_options = None
  _globals['_DELETEFAVORITEREQUEST'].fields_by_name['name']._serialized_options = b'\340A\002\372A%\n#favorite.api.audiotool.com/Favorite'
  _globals['_CREATEFAVORITEREQUEST']._serialized_start=132
  _globals['_CREATEFAVORITEREQUEST']._serialized_end=417
  _globals['_CREATEFAVORITERESPONSE']._serialized_start=419
  _globals['_CREATEFAVORITERESPONSE']._serialized_end=443
  _globals['_DELETEFAVORITEREQUEST']._serialized_start=445
  _globals['_DELETEFAVORITEREQUEST']._serialized_end=533
  _globals['_DELETEFAVORITERESPONSE']._serialized_start=535
  _globals['_DELETEFAVORITERESPONSE']._serialized_end=559
  _globals['_FAVORITESERVICE']._serialized_start=562
  _globals['_FAVORITESERVICE']._serialized_end=805
# @@protoc_insertion_point(module_scope)
