# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audiotool/auth/v1/auth_service.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'audiotool/auth/v1/auth_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from audiotool.auth.v1 import auth_pb2 as audiotool_dot_auth_dot_v1_dot_auth__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$audiotool/auth/v1/auth_service.proto\x12\x11\x61udiotool.auth.v1\x1a\x1c\x61udiotool/auth/v1/auth.proto\"\x12\n\x10GetWhoamiRequest\"F\n\x11GetWhoamiResponse\x12\x31\n\x06whoami\x18\x01 \x01(\x0b\x32\x19.audiotool.auth.v1.WhoamiR\x06whoami\"!\n\x1fListPersonalAccessTokensRequest\"b\n ListPersonalAccessTokensResponse\x12>\n\x06tokens\x18\x01 \x03(\x0b\x32&.audiotool.auth.v1.PersonalAccessTokenR\x06tokens\"`\n CreatePersonalAccessTokenRequest\x12<\n\x05token\x18\x01 \x01(\x0b\x32&.audiotool.auth.v1.PersonalAccessTokenR\x05token\"a\n!CreatePersonalAccessTokenResponse\x12<\n\x05token\x18\x01 \x01(\x0b\x32&.audiotool.auth.v1.PersonalAccessTokenR\x05token\"6\n DeletePersonalAccessTokenRequest\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\"#\n!DeletePersonalAccessTokenResponse2\x85\x04\n\x0b\x41uthService\x12X\n\tGetWhoami\x12#.audiotool.auth.v1.GetWhoamiRequest\x1a$.audiotool.auth.v1.GetWhoamiResponse\"\x00\x12\x85\x01\n\x18ListPersonalAccessTokens\x12\x32.audiotool.auth.v1.ListPersonalAccessTokensRequest\x1a\x33.audiotool.auth.v1.ListPersonalAccessTokensResponse\"\x00\x12\x88\x01\n\x19\x43reatePersonalAccessToken\x12\x33.audiotool.auth.v1.CreatePersonalAccessTokenRequest\x1a\x34.audiotool.auth.v1.CreatePersonalAccessTokenResponse\"\x00\x12\x88\x01\n\x19\x44\x65letePersonalAccessToken\x12\x33.audiotool.auth.v1.DeletePersonalAccessTokenRequest\x1a\x34.audiotool.auth.v1.DeletePersonalAccessTokenResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audiotool.auth.v1.auth_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETWHOAMIREQUEST']._serialized_start=89
  _globals['_GETWHOAMIREQUEST']._serialized_end=107
  _globals['_GETWHOAMIRESPONSE']._serialized_start=109
  _globals['_GETWHOAMIRESPONSE']._serialized_end=179
  _globals['_LISTPERSONALACCESSTOKENSREQUEST']._serialized_start=181
  _globals['_LISTPERSONALACCESSTOKENSREQUEST']._serialized_end=214
  _globals['_LISTPERSONALACCESSTOKENSRESPONSE']._serialized_start=216
  _globals['_LISTPERSONALACCESSTOKENSRESPONSE']._serialized_end=314
  _globals['_CREATEPERSONALACCESSTOKENREQUEST']._serialized_start=316
  _globals['_CREATEPERSONALACCESSTOKENREQUEST']._serialized_end=412
  _globals['_CREATEPERSONALACCESSTOKENRESPONSE']._serialized_start=414
  _globals['_CREATEPERSONALACCESSTOKENRESPONSE']._serialized_end=511
  _globals['_DELETEPERSONALACCESSTOKENREQUEST']._serialized_start=513
  _globals['_DELETEPERSONALACCESSTOKENREQUEST']._serialized_end=567
  _globals['_DELETEPERSONALACCESSTOKENRESPONSE']._serialized_start=569
  _globals['_DELETEPERSONALACCESSTOKENRESPONSE']._serialized_end=604
  _globals['_AUTHSERVICE']._serialized_start=607
  _globals['_AUTHSERVICE']._serialized_end=1124
# @@protoc_insertion_point(module_scope)
