# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audiotool/auth/v1/auth.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'audiotool/auth/v1/auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x61udiotool/auth/v1/auth.proto\x12\x11\x61udiotool.auth.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8e\x01\n\x06Whoami\x12\x1b\n\tuser_name\x18\x01 \x01(\tR\x08userName\x12\x14\n\x05roles\x18\x02 \x03(\tR\x05roles\x12*\n\x11is_email_verified\x18\x03 \x01(\x08R\x0fisEmailVerified\x12%\n\x0egranted_scopes\x18\x04 \x03(\tR\rgrantedScopes\"\xb2\x03\n\x13PersonalAccessToken\x12\x17\n\x04name\x18\x01 \x01(\tB\x03\xe0\x41\x08R\x04name\x12!\n\x0c\x64isplay_name\x18\x02 \x01(\tR\x0b\x64isplayName\x12 \n\tuser_name\x18\x03 \x01(\tB\x03\xe0\x41\x03R\x08userName\x12&\n\x0c\x61\x63\x63\x65ss_token\x18\x04 \x01(\tB\x03\xe0\x41\x03R\x0b\x61\x63\x63\x65ssToken\x12@\n\x0b\x63reate_time\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x03\xe0\x41\x03R\ncreateTime\x12;\n\x0b\x65xpire_time\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\nexpireTime\x12\x43\n\rlast_use_time\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x03\xe0\x41\x03R\x0blastUseTime:Q\xea\x41N\n\x1dtoken.api.audiotool.com/Token\x12\x1eusers/{username}/tokens/{uuid}*\x06tokens2\x05tokenb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audiotool.auth.v1.auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PERSONALACCESSTOKEN'].fields_by_name['name']._loaded_options = None
  _globals['_PERSONALACCESSTOKEN'].fields_by_name['name']._serialized_options = b'\340A\010'
  _globals['_PERSONALACCESSTOKEN'].fields_by_name['user_name']._loaded_options = None
  _globals['_PERSONALACCESSTOKEN'].fields_by_name['user_name']._serialized_options = b'\340A\003'
  _globals['_PERSONALACCESSTOKEN'].fields_by_name['access_token']._loaded_options = None
  _globals['_PERSONALACCESSTOKEN'].fields_by_name['access_token']._serialized_options = b'\340A\003'
  _globals['_PERSONALACCESSTOKEN'].fields_by_name['create_time']._loaded_options = None
  _globals['_PERSONALACCESSTOKEN'].fields_by_name['create_time']._serialized_options = b'\340A\003'
  _globals['_PERSONALACCESSTOKEN'].fields_by_name['last_use_time']._loaded_options = None
  _globals['_PERSONALACCESSTOKEN'].fields_by_name['last_use_time']._serialized_options = b'\340A\003'
  _globals['_PERSONALACCESSTOKEN']._loaded_options = None
  _globals['_PERSONALACCESSTOKEN']._serialized_options = b'\352AN\n\035token.api.audiotool.com/Token\022\036users/{username}/tokens/{uuid}*\006tokens2\005token'
  _globals['_WHOAMI']._serialized_start=145
  _globals['_WHOAMI']._serialized_end=287
  _globals['_PERSONALACCESSTOKEN']._serialized_start=290
  _globals['_PERSONALACCESSTOKEN']._serialized_end=724
# @@protoc_insertion_point(module_scope)
